package com.java.inherMtd.internal;

public class Runner {
    public static void main(String[] args) {
        HP hp = new HP(30000, "workstation");
        hp.pc();
        HP lp = new Laptop();
        lp.pc();
        Laptop laptop = new Laptop();
        laptop.pc();
        laptop.ram();
        Castclass castclass = new Castclass();
        castclass.hpz(hp);
        castclass.hpz(lp);
        HP hp1 = new HP(5000, "pavilion");
        hp1.toString();
        System.out.println(hp1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Shirt shirt = new Shirt("cotton", 500);
        shirt.clt();
        Shirt srt = new Pant();
        srt.clt();
        Pant pant = new Pant();
        pant.clt();
        pant.pt();
        Castclass leni = new Castclass();
        leni.lenin(srt);
        leni.lenin(pant);
        Shirt shrt = new Shirt("cotton", 500);
        shrt.toString();
        System.out.println(shrt);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Sun sun = new Sun(12000, 1000);
        sun.slr();
        Sun sn = new Earth();
        sn.slr();
        Earth earth = new Earth();
        earth.lnd();
        earth.slr();
        Castclass erth = new Castclass();
        erth.hpz(sn);
        erth.hpz(earth);
        Sun sun1 = new Sun(12000, 1000);
        sun1.toString();
        System.out.println(sun1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Tree tree = new Tree(50, true);
        tree.tree();
        Tree tr = new Plant();
        tr.tree();
        Plant plant = new Plant();
        plant.plt();
        plant.tree();
        Castclass pln = new Castclass();
        pln.tre(tree);
        pln.tre(plant);
        Tree tree1 = new Tree(50, true);
        tree1.toString();
        System.out.println(tree1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Pen pen = new Pen("celo", 10);
        pen.wrt();
        Pen pn = new Pencil();
        pn.wrt();
        Pencil pencil = new Pencil();
        pencil.pncl();
        pencil.wrt();
        Castclass cil = new Castclass();
        cil.pen(pen);
        cil.pen(pencil);
        Pen pen1 = new Pen("celo", 10);
        pen1.toString();
        System.out.println(pen1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Bedsheet bedsheet = new Bedsheet(20, 40);
        bedsheet.bdst();
        Bedsheet bdt = new Pillow();
        bdt.bdst();
        Pillow pillow = new Pillow();
        pillow.pill();
        pillow.bdst();
        Castclass shet = new Castclass();
        shet.bed(bedsheet);
        shet.bed(pillow);
        Bedsheet bed = new Bedsheet(20, 40);
        bed.toString();
        System.out.println(bed);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Alchol alchol = new Alchol(90, "BW");
        alchol.alc();
        Alchol alh = new Beer();
        alh.alc();
        Beer beer = new Beer();
        beer.alc();
        beer.ber();
        Castclass alch = new Castclass();
        alch.alco(alchol);
        alch.alco(beer);
        Alchol alco = new Alchol(90, "BW");
        alco.toString();
        System.out.println(alco);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Samsung samsung = new Samsung(20000, true);
        samsung.sam();
        Samsung smng = new Mobile();
        Mobile mobile = new Mobile();
        mobile.mbl();
        mobile.sam();
        Castclass sam = new Castclass();
        sam.sug(samsung);
        sam.sug(mobile);
        Samsung samsung1 = new Samsung(20000, true);
        samsung1.toString();
        System.out.println(samsung1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Mac mac = new Mac("apple", 12300);
        mac.Mc();
        ;
        Mac mc = new Tab();
        mc.Mc();
        Tab tab = new Tab();
        tab.Mc();
        tab.tab();
        Castclass macc = new Castclass();
        macc.mc(mac);
        macc.mc(tab);
        Mac mac1 = new Mac("apple", 12300);
        mac1.toString();
        System.out.println(mac1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Rocket rocket = new Rocket(1200, "PSLV");
        rocket.rct();
        Rocket rct = new Sattelite();
        rct.rct();
        Sattelite sattelite = new Sattelite();
        sattelite.rct();
        sattelite.stlt();
        Castclass rock = new Castclass();
        rock.roc(rocket);
        rock.roc(sattelite);
        Rocket rocket1 = new Rocket(1200, "PSLV");
        rocket1.toString();
        System.out.println(rocket1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Bird bird = new Bird("brown", 10);
        bird.brd();
        Bird bid = new Eagle();
        bid.brd();
        Eagle eagle = new Eagle();
        eagle.brd();
        eagle.egle();
        Castclass kiw = new Castclass();
        kiw.brd(bid);
        kiw.brd(eagle);
        Bird bird1 = new Bird("brown", 10);
        bird1.toString();
        System.out.println(bird1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Flover flover = new Flover("red", true);
        flover.flr();
        Flover fvr = new Rose();
        fvr.flr();
        Rose rose = new Rose();
        rose.flr();
        rose.rse();
        Castclass rse = new Castclass();
        rse.flower(flover);
        rse.flower(rose);
        Flover flover1 = new Flover("red", true);
        flover1.toString();
        System.out.println(flover1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Navagraha navagraha = new Navagraha(20, 2012);
        navagraha.nava();
        Navagraha nvg = new Darshan();
        nvg.nava();
        Darshan darshan = new Darshan();
        darshan.darshu();
        darshan.nava();
        Castclass dasa = new Castclass();
        dasa.nava(navagraha);
        dasa.nava(darshan);
        Navagraha navagraha1 = new Navagraha(20, 2012);
        navagraha1.toString();
        System.out.println(navagraha1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Bottle bottle = new Bottle(1, "water");
        bottle.btl();
        Bottle btl = new Glass();
        btl.btl();
        Glass glass = new Glass();
        glass.gls();
        glass.btl();
        Castclass kln = new Castclass();
        kln.Btl(bottle);
        kln.Btl(glass);
        Bottle bottle1 = new Bottle(1, "water");
        bottle1.toString();
        System.out.println(bottle1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Seed seed = new Seed(30, "mango");
        seed.sed();
        Seed sd = new Friut();
        Friut friut = new Friut();
        friut.frt();
        friut.sed();
        Castclass frut = new Castclass();
        frut.nut(friut);
        frut.nut(seed);
        Seed seed1 = new Seed(30, "mango");
        seed1.toString();
        System.out.println(seed1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Sudeep sudeep = new Sudeep("sudeep", "max");
        sudeep.sude();
        Sudeep sup = new MAX();
        sup.sude();
        MAX max = new MAX();
        max.mx();
        max.sude();
        Castclass sdp = new Castclass();
        sdp.sudee(sup);
        sdp.sudee(max);
        Sudeep sudeep1 = new Sudeep("sudeep", "max");
        sudeep1.toString();
        System.out.println(sudeep1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Ore ore = new Ore(2, 106);
        ore.ore();
        Ore or = new Iron();
        or.ore();
        Iron irn = new Iron();
        irn.iron();
        irn.ore();
        Castclass iron = new Castclass();
        iron.mgn(ore);
        iron.mgn(irn);
        Ore o = new Ore(2, 106);
        o.toString();
        System.out.println(o);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Bed bed1 = new Bed("sleepWell", "foam");
        bed1.bed();
        Bed bd = new Foam();
        bd.bed();
        Foam foam = new Foam();
        foam.bed();
        foam.foam();
        Castclass fm = new Castclass();
        fm.soft(bd);
        fm.soft(foam);
        Bed bed2 = new Bed("sleepWell", "foam");
        bed2.toString();
        System.out.println(bed2);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        LG lg = new LG(2500, true);
        lg.lg();
        LG lg1 = new Fridge();
        lg1.lg();
        Fridge fridge = new Fridge();
        fridge.fridge();
        fridge.lg();
        Castclass frg = new Castclass();
        frg.frige(lg);
        frg.frige(fridge);
        LG lg2 = new LG(2500, true);
        lg2.toString();
        System.out.println(lg2);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        IFB ifb = new IFB("IFB", 13);
        ifb.wash();
        IFB ifb1 = new Washingmch();
        ifb1.wash();
        Washingmch washingmch = new Washingmch();
        washingmch.mch();
        washingmch.wash();
        Castclass wasn = new Castclass();
        wasn.mchn(ifb);
        wasn.mchn(washingmch);
        IFB ifb2 = new IFB("IFB", 13);
        ifb2.toString();
        System.out.println(ifb2);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Voltas voltas = new Voltas(12, true);
        voltas.vlts();
        Voltas vlt = new AC();
        vlt.vlts();
        AC ac = new AC();
        ac.Aircool();
        ac.vlts();
        Castclass cool = new Castclass();
        cool.volt(vlt);
        cool.volt(ac);
        Voltas voltas1 = new Voltas(12, true);
        voltas1.toString();
        System.out.println(voltas1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Door door = new Door(7, 4);
        door.dor();
        Door dor = new Window();
        dor.dor();
        Window window = new Window();
        window.dor();
        ;
        window.Windo();
        Castclass dr = new Castclass();
        dr.sefe(door);
        dr.sefe(window);
        Door door1 = new Door(7, 4);
        door1.toString();
        System.out.println(door1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Billagate billagate = new Billagate("billgates", "Microsoft");
        billagate.bill();
        Billagate bil = new Micro();
        bil.bill();
        Micro micro = new Micro();
        micro.micro();
        micro.bill();
        Castclass gate = new Castclass();
        gate.gates(billagate);
        gate.gates(micro);
        Billagate billagate1 = new Billagate("billgates", "Microsoft");
        billagate1.toString();
        System.out.println(billagate1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Skybag skybag = new Skybag(6, "Skybag");
        skybag.sky();
        Skybag bag = new Bag();
        bag.sky();
        Bag bag1 = new Bag();
        bag1.bag();
        bag1.sky();
        Castclass bg = new Castclass();
        bg.sky(skybag);
        bg.sky(bag);
        Skybag skybag1 = new Skybag(6, "Skybag");
        skybag1.toString();
        System.out.println(skybag1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Fruit fruit = new Fruit("Apple", false);
        fruit.fruit();
        Fruit frt = new Apple();
        frt.fruit();
        Apple apple = new Apple();
        apple.apple();
        apple.fruit();
        Castclass frit = new Castclass();
        frit.frut(fruit);
        frit.frut(apple);
        Fruit fruit1 = new Fruit("Apple", false);
        fruit1.toString();
        System.out.println(fruit1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Ganesh ganesh = new Ganesh("ganesh", "zoom");
        ganesh.gani();
        Ganesh gani = new Zoom();
        Zoom zoom = new Zoom();
        zoom.gani();
        zoom.zoom();
        Castclass gan = new Castclass();
        gan.gani(ganesh);
        gan.gani(zoom);
        Ganesh ganesh1 = new Ganesh("ganesh", "zoom");
        ganesh1.toString();
        System.out.println(ganesh1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Hair hair = new Hair("blonde", "curly");
        hair.hair();
        Hair hir = new Band();
        hir.hair();
        Band band = new Band();
        band.band();
        band.hair();
        Castclass smp = new Castclass();
        smp.samp(hir);
        smp.samp(band);
        Hair hair1 = new Hair("blonde", "curly");
        hair1.toString();
        System.out.println(hair1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Oven oven = new Oven(100, "sam");
        oven.oven();
        Oven ovn = new Heat();
        ovn.oven();
        Heat heat = new Heat();
        heat.heat();
        heat.oven();
        Castclass ht = new Castclass();
        ht.ovn(ovn);
        ht.ovn(heat);
        Oven oven1 = new Oven(100, "sam");
        oven1.toString();
        System.out.println(oven1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Gun gun = new Gun(100, true);
        gun.gun();
        Gun gn = new MP5();
        gn.gun();
        MP5 mp5 = new MP5();
        mp5.gun();
        mp5.mp();
        Castclass rfl = new Castclass();
        rfl.Rifl(gun);
        rfl.Rifl(mp5);
        Gun gun1 = new Gun(100, true);
        gun1.toString();
        System.out.println(gun1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        India india = new India("NM", 31);
        india.india();
        India indi = new Delhi();
        indi.india();
        Delhi delhi = new Delhi();
        delhi.delhi();
        delhi.india();
        Castclass deli = new Castclass();
        deli.indus(india);
        deli.indus(delhi);
        India india1 = new India("NM", 31);
        india1.toString();
        System.out.println(india1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Paper paper = new Paper("Plain", 0.05);
        paper.paper();
        Paper ppr = new A4();
        ppr.paper();
        A4 a4 = new A4();
        a4.appr();
        a4.paper();
        Castclass pap = new Castclass();
        pap.buff(paper);
        pap.buff(a4);
        Paper paper3 = new Paper("Plain", 0.05);
        paper3.toString();
        System.out.println(paper3);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Honda honda = new Honda(23, true);
        honda.honda();
        Honda hond = new Civic();
        hond.honda();
        Civic civic = new Civic();
        civic.civic();
        civic.honda();
        Castclass hon = new Castclass();
        hon.hond(hond);
        hon.hond(civic);
        Honda honda1 = new Honda(23, true);
        honda1.toString();
        System.out.println(honda1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Suzuki suzuki = new Suzuki("swift", 900000);
        suzuki.suzuki();
        Suzuki suzu = new Swift();
        suzu.suzuki();
        Swift swift = new Swift();
        swift.swift();
        swift.suzuki();
        Castclass swif = new Castclass();
        swif.suzu(suzuki);
        swif.suzu(swift);
        Suzuki suzuki1 = new Suzuki("swift", 900000);
        suzuki1.toString();
        System.out.println(suzuki1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Yamaha yamaha = new Yamaha("yaamha", 102000);
        yamaha.yamaha();
        Yamaha yamaha1 = new RX();
        yamaha.yamaha();
        RX rx = new RX();
        rx.rx();
        rx.yamaha();
        Castclass yam = new Castclass();
        yam.yamah(yamaha);
        yam.yamah(rx);
        Yamaha yamaha2 = new Yamaha("yaamha", 102000);
        yamaha2.toString();
        System.out.println(yamaha2);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        TVS tvs = new TVS(24935, "jupiter");
        tvs.tvs();
        TVS tvs1 = new Jpiter();
        tvs1.tvs();
        Jpiter jpiter = new Jpiter();
        jpiter.Jpter();
        jpiter.tvs();
        Castclass ap = new Castclass();
        ap.tvs(tvs);
        ap.tvs(jpiter);
        TVS tvs2 = new TVS(24935, "jupiter");
        tvs2.toString();
        System.out.println(tvs2);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Hero hero = new Hero(true, 180);
        hero.hero();
        Hero hero1 = new Cdh();
        hero1.hero();
        Cdh cdh = new Cdh();
        cdh.cdh();
        cdh.hero();
        Castclass her = new Castclass();
        her.hero(hero1);
        her.hero(cdh);
        Hero hero2 = new Hero(true, 180);
        hero2.toString();
        System.out.println(hero2);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        JCB jcb = new JCB("hitachi", 34536);
        jcb.jcb();
        JCB jcb1 = new Hita();
        jcb1.jcb();
        Hita hita = new Hita();
        hita.hita();
        hita.jcb();
        Castclass hit = new Castclass();
        hit.jcb(jcb);
        hit.jcb(hita);
        JCB jcb2 = new JCB("hitachi", 34536);
        jcb2.toString();
        System.out.println(jcb2);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        RCB rcb = new RCB("RCB", "Virat");
        rcb.rcb();
        RCB rcb1 = new Virat();
        rcb1.rcb();
        Virat virat = new Virat();
        virat.rcb();
        virat.virat();
        Castclass rc = new Castclass();
        rc.bang(rcb);
        rc.bang(virat);
        RCB rcb2 = new RCB("RCB", "Virat");
        rcb2.toString();
        System.out.println(rcb2);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Karnataka karnataka = new Karnataka(31, "karnataka");
        karnataka.state();
        Karnataka karnataka1 = new Benlore();
        karnataka.state();
        Benlore benlore = new Benlore();
        benlore.bnglr();
        benlore.state();
        Castclass kar = new Castclass();
        kar.karu(karnataka);
        kar.karu(benlore);
        Karnataka karnataka2 = new Karnataka(31, "karnataka");
        karnataka2.toString();
        System.out.println(karnataka2);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Water water = new Water(90, true);
        water.water();
        ;
        Water water1 = new Fish();
        water1.water();
        Fish fish = new Fish();
        fish.fish();
        fish.water();
        Castclass min = new Castclass();
        min.neer(water);
        min.neer(fish);
        Water water2 = new Water(90, true);
        water2.toString();
        System.out.println(water2);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Brain brain = new Brain(2, 'f');
        brain.brain();
        Brain brain1 = new Nueral();
        brain1.brain();
        Nueral nueral = new Nueral();
        nueral.brain();
        nueral.nuerl();
        Castclass neu = new Castclass();
        neu.ment(brain);
        neu.ment(nueral);
        Brain brain2 = new Brain(2, 'f');
        brain2.toString();
        System.out.println(brain2);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        CPU cpu = new CPU(16, "intel");
        cpu.cpu();
        CPU cpu1 = new Procces();
        cpu1.cpu();
        Procces procces = new Procces();
        procces.cpu();
        procces.Proces();
        Castclass cp = new Castclass();
        cp.proces(cpu);
        cp.proces(procces);
        CPU cpu2 = new CPU(16, "intel");
        cpu2.toString();
        System.out.println(cpu2);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Parle parle = new Parle("parle", 20);
        parle.parle();
        Parle parle1 = new G();
        parle1.parle();
        G g = new G();
        g.G();
        g.parle();
        Castclass par = new Castclass();
        par.par(parle);
        par.par(g);
        Parle parle2 = new Parle("parle", 20);
        parle2.toString();
        System.out.println(parle2);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Mari mari = new Mari(20, "whaet");
        mari.mari();
        Mari mari1 = new Lite();
        mari1.mari();
        Lite lite = new Lite();
        lite.lite();
        lite.mari();
        Castclass mar = new Castclass();
        mar.maru(mari);
        mar.maru(lite);
        Mari mari2 = new Mari(20, "whaet");
        mari2.toString();
        System.out.println(mari2);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Chrdurga chrdurga = new Chrdurga(394209, "marikanive");
        chrdurga.ctd();
        Clk clk = new Clk();
        clk.clk();
        clk.ctd();
        Castclass cld = new Castclass();
        cld.durga(chrdurga);
        cld.durga(clk);
        Chrdurga chrdurga2 = new Chrdurga(394209, "marikanive");
        chrdurga2.toString();
        System.out.println(chrdurga2);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Davanagere davanagere = new Davanagere("davangere", 1242242);
        davanagere.dvg();
        Davanagere davanagere1 = new Harihar();
        davanagere1.dvg();
        Harihar harihar = new Harihar();
        harihar.dvg();
        harihar.hari();
        Castclass hara = new Castclass();
        hara.davn(davanagere);
        hara.davn(harihar);
        Davanagere davanagere2 = new Davanagere("davangere", 1242242);
        davanagere2.toString();
        System.out.println(davanagere2);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Thumkur thumkur = new Thumkur("thumukr", 5358033);
        thumkur.tmkr();
        Thumkur thumkur1 = new Pavgada();
        thumkur1.tmkr();
        Pavgada pavgada = new Pavgada();
        pavgada.pvgd();
        pavgada.tmkr();
        Castclass pava = new Castclass();
        pava.tmkr(thumkur);
        pava.tmkr(pavgada);
        Thumkur thumkur2 = new Thumkur("thumukr", 5358033);
        thumkur2.toString();
        System.out.println();
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Shivmoga shivmoga = new Shivmoga("Shivmogga", 234935511);
        shivmoga.shmg();
        Shivmoga shivmoga1 = new Sagara();
        shivmoga1.shmg();
        Sagara sagara = new Sagara();
        sagara.sagara();
        sagara.shmg();
        Castclass sag = new Castclass();
        sag.shiv(shivmoga);
        sag.shiv(sagara);
        Shivmoga shivmoga2 = new Shivmoga("Shivmogga", 234935511);
        shivmoga2.toString();
        System.out.println(shivmoga2);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Java java = new Java("java", "oracle");
        java.jva();
        Java java1 = new Jvm();
        java1.jva();
        Jvm jvm = new Jvm();
        jvm.jva();
        jvm.jva();
        Castclass ja = new Castclass();
        ja.jdk(java);
        ja.jdk(jvm);
        Java java2 = new Java("java", "oracle");
        java2.toString();
        System.out.println(java2);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Romeo romeo = new Romeo("romeo", "juliet");
        romeo.romeo();
        Romeo romeo1 = new Juleat();
        romeo1.romeo();
        Juleat juleat = new Juleat();
        juleat.juleat();
        juleat.juleat();
        Castclass jlt = new Castclass();
        jlt.rom(romeo);
        jlt.rom(juleat);
        Romeo romeo2 = new Romeo("romeo", "juliet");
        romeo2.toString();
        System.out.println(romeo2);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Wifi wifi = new Wifi(842462462, 15);
        wifi.wifi();
        Wifi wifi1 = new Hotspot();
        wifi1.wifi();
        Hotspot hotspot = new Hotspot();
        hotspot.hotspot();
        Castclass wfi = new Castclass();
        wfi.wi(wifi);
        wfi.wi(hotspot);
        Wifi wifi2 = new Wifi(842462462, 15);
        wifi2.toString();
        System.out.println(wifi2);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Lion lion = new Lion(false, "non veg");
        lion.lion();
        Lion lion1 = new Cat();
        lion1.lion();
        Cat cat = new Cat();
        Castclass lio = new Castclass();
        lio.leo(lion);
        lio.leo(cat);
        Lion lion2 = new Lion(false, "non veg");
        lion2.toString();
        System.out.println(lion2);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Table table = new Table(4, "dining");
        table.furniture();
        Table wt = new WoodenTable();
        wt.furniture();
        WoodenTable woodenTable = new WoodenTable();
        woodenTable.furniture();
        woodenTable.polish();
        Castclass tbl = new Castclass();
        tbl.furn(table);
        tbl.furn(woodenTable);
        Table table1 = new Table(4, "dining");
        table1.toString();
        System.out.println(table1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Towel towel = new Towel("cotton", 24);
        towel.cloth();
        Towel bt = new BathTowel();
        bt.cloth();
        BathTowel bathTowel = new BathTowel();
        bathTowel.cloth();
        bathTowel.absorb();
        Castclass tvl = new Castclass();
        tvl.tovel(towel);
        tvl.tovel(bathTowel);
        Towel Towel1 = new Towel("cotton", 24);
        Towel1.toString();
        System.out.println(Towel1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Curtain curtain = new Curtain("window", "white");
        curtain.fabric();
        Curtain wc = new WindowCurtain();
        wc.fabric();
        WindowCurtain windowCurtain = new WindowCurtain();
        windowCurtain.fabric();
        windowCurtain.cover();
        Castclass crt = new Castclass();
        crt.curt(curtain);
        crt.curt(windowCurtain);
        Curtain curtain1 = new Curtain("window", "white");
        curtain1.toString();
        System.out.println(curtain1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Truck truck = new Truck(8, "tata");
        truck.load();
        Truck mt = new MiniTruck();
        mt.load();
        MiniTruck miniTruck = new MiniTruck();
        miniTruck.load();
        miniTruck.capacity();
        Castclass tck = new Castclass();
        tck.truk(truck);
        tck.truk(miniTruck);
        Truck truck1 = new Truck(8, "tata");
        truck1.toString();
        System.out.println(truck1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        IronBox ironBox = new IronBox("Steam", 100);
        ironBox.heat();
        IronBox si = new SteamIron();
        si.heat();
        SteamIron steamIron = new SteamIron();
        steamIron.heat();
        steamIron.steam();
        Castclass irnx = new Castclass();
        irnx.irnbx(ironBox);
        irnx.irnbx(steamIron);
        IronBox ironBox1 = new IronBox("Steam", 100);
        ironBox1.toString();
        System.out.println(ironBox1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Missile missile = new Missile("tejas", 4633);
        missile.launch();
        Missile gm = new GuidedMissile();
        gm.launch();
        GuidedMissile guidedMissile = new GuidedMissile();
        guidedMissile.launch();
        guidedMissile.target();
        Castclass miss = new Castclass();
        miss.misle(missile);
        miss.misle(guidedMissile);
        Missile missile1 = new Missile("tejas", 4633);
        missile1.toString();
        System.out.println(missile1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Land land = new Land("raamu", 5635673);
        land.property();
        Land agLand = new AgriLand();
        agLand.property();
        AgriLand agriculturalLand = new AgriLand();
        agriculturalLand.property();
        agriculturalLand.cultivate();
        Castclass ld = new Castclass();
        Land land1 = new Land("raamu", 5635673);
        land1.toString();
        System.out.println(land1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        ld.lnd(land);
        ld.lnd(agriculturalLand);
        Ragi ragi = new Ragi(2, 100);
        ragi.grain();
        Ragi ragi1 = new RagiMalt();
        ragi1.grain();
        RagiMalt ragiMalt = new RagiMalt();
        ragiMalt.drink();
        ragiMalt.grain();
        Castclass rg = new Castclass();
        rg.rag(ragi);
        rg.rag(ragiMalt);
        Ragi ragi2 = new Ragi(2, 100);
        ragi2.toString();
        System.out.println(ragi2);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        GoldChain gold = new GoldChain(10, 24);
        gold.shine();
        GoldChain fancy = new Gold();
        fancy.shine();
        Gold fancyGold = new Gold();
        fancyGold.shine();
        fancyGold.design();
        Castclass gd = new Castclass();
        gd.goldch(gold);
        gd.goldch(fancyGold);
        GoldChain goldChain = new GoldChain(10, 24);
        goldChain.toString();
        System.out.println(goldChain);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Battery battery = new Battery(4959, "exide");
        battery.power();
        Battery rb = new Exide();
        rb.power();
        Exide rechargeableBattery = new Exide();
        rechargeableBattery.power();
        rechargeableBattery.charge();
        Castclass btry = new Castclass();
        btry.btry(battery);
        btry.btry(rechargeableBattery);
        Battery battery1 = new Battery(4959, "exide");
        battery1.toString();
        System.out.println(battery1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Tank tank = new Tank("battle", 3555);
        tank.fire();
        Tank bttl = new BattleTank();
        bttl.fire();
        BattleTank battleTank = new BattleTank();
        battleTank.fire();
        battleTank.armor();
        Castclass btlnk = new Castclass();
        btlnk.tnk(tank);
        btlnk.tnk(battleTank);
        Tank tank1 = new Tank("battle", 3555);
        tank1.toString();
        System.out.println(tank1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Bow bow = new Bow("wooden", 20);
        bow.shoot();
        Bow lb = new LongBow();
        lb.shoot();
        LongBow longBow = new LongBow();
        longBow.shoot();
        longBow.range();
        Castclass bo = new Castclass();
        bo.bw(bow);
        bo.bw(longBow);
        Bow bow1 = new Bow("wooden", 20);
        bow1.toString();
        System.out.println(bow1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Bowl bowl = new Bowl(12, 100);
        bowl.hold();
        Bowl sb = new SoupBowl();
        sb.hold();
        SoupBowl soupBowl = new SoupBowl();
        soupBowl.hold();
        soupBowl.serve();
        Castclass spbl = new Castclass();
        spbl.bwl(bowl);
        spbl.bwl(soupBowl);
        Bowl bowl1 = new Bowl(12, 100);
        bowl1.toString();
        System.out.println(bowl1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Rice rice = new Rice("Basmati", 200);
        rice.cook();
        Rice basmati = new BasmatiRice();
        basmati.cook();
        BasmatiRice basmatiRice = new BasmatiRice();
        basmatiRice.cook();
        basmatiRice.aroma();
        Castclass bsmt = new Castclass();
        bsmt.rce(rice);
        bsmt.rce(basmatiRice);
        Rice rice1 = new Rice("Basmati", 200);
        rice1.toString();
        System.out.println(rice1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        BislariBottle bottle2 = new BislariBottle("1L", 50);
        bottle2.fill();
        BislariBottle wb = new WaterBottle();
        wb.fill();
        WaterBottle waterBottle = new WaterBottle();
        waterBottle.fill();
        waterBottle.drink();
        Castclass biwtr = new Castclass();
        biwtr.bisl(bottle2);
        biwtr.bisl(waterBottle);
        BislariBottle bottle4 = new BislariBottle("1L", 50);
        bottle4.toString();
        System.out.println(bottle4);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Printer printer = new Printer("HP LaserJet", 25000);
        printer.print();
        Printer lp1 = new LaserPrinter();
        lp1.print();
        LaserPrinter laserPrinter = new LaserPrinter();
        laserPrinter.print();
        laserPrinter.speed();
        Castclass prt = new Castclass();
        prt.print(printer);
        prt.print(laserPrinter);
        Printer printer1 = new Printer("HP LaserJet", 25000);
        printer1.toString();
        System.out.println(printer1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Kurtha kurtha = new Kurtha("Cotton", 1500);
        kurtha.wear();
        Kurtha designer = new DesiKurtha();
        designer.wear();
        DesiKurtha designerKurtha = new DesiKurtha();
        designerKurtha.wear();
        designerKurtha.embroidery();
        Castclass dek = new Castclass();
        dek.dress(kurtha);
        dek.dress(designerKurtha);
        Kurtha kurtha1 = new Kurtha("Cotton", 1500);
        kurtha1.toString();
        System.out.println(kurtha1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Xerox xerox = new Xerox("Canon ColorXerox", 5000);
        xerox.copy();
        Xerox color = new ColorXerox();
        color.copy();
        ColorXerox colorXerox = new ColorXerox();
        colorXerox.copy();
        Castclass xrx = new Castclass();
        xrx.xrx(xerox);
        xrx.xrx(colorXerox);
        Xerox xerox1 = new Xerox("Canon ColorXerox", 5000);
        xerox1.toString();
        System.out.println(xerox1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Train train = new Train("Shinkansen", 320);
        train.move();
        Train bullet = new BulletTrain();
        bullet.move();
        BulletTrain bulletTrain = new BulletTrain();
        bulletTrain.move();
        Castclass tri = new Castclass();
        tri.trn(train);
        tri.trn(bulletTrain);
        bulletTrain.highSpeed();
        Train train1 = new Train("Shinkansen", 320);
        train1.toString();
        System.out.println(train1);
        Spoon spoon = new Spoon("Silver", 1200);
        spoon.scoop();
        Spoon silver = new SilverSpoon();
        silver.scoop();
        SilverSpoon silverSpoon = new SilverSpoon();
        silverSpoon.scoop();
        silverSpoon.shine();
        Castclass spon = new Castclass();
        spon.spn(spoon);
        spon.spn(silverSpoon);
        Spoon spoon1 = new Spoon("Silver", 1200);
        spoon1.toString();
        System.out.println(spoon1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");

        Fork fork = new Fork("SaladFork", 300);
        fork.pick();
        Fork salad = new SaladFork();
        salad.pick();
        SaladFork saladFork = new SaladFork();
        saladFork.pick();
        saladFork.grip();
        Castclass fr = new Castclass();
        fr.frk(fork);
        fr.frk(saladFork);
        Fork fork1 = new Fork("SaladFork", 300);
        fork1.toString();
        System.out.println(fork1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Film film = new Film("Planet Earth", 50);
        film.play();
        Film doc = new DocumentaryFilm();
        doc.play();
        DocumentaryFilm documentary = new DocumentaryFilm();
        documentary.play();
        documentary.educate();
        Castclass mov = new Castclass();
        mov.flm(film);
        mov.flm(documentary);
        Film film1 = new Film("Planet Earth", 50);
        film1.toString();
        System.out.println(film1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Switch sw = new Switch("Philips", 1200);
        sw.turnOn();
        Switch smart = new SmartSwitch();
        smart.turnOn();
        SmartSwitch smartSwitch = new SmartSwitch();
        smartSwitch.turnOn();
        smartSwitch.schedule();
        Castclass swt = new Castclass();
        swt.swth(sw);
        swt.swth(smartSwitch);
        Switch sw1 = new Switch("Philips", 1200);
        sw1.toString();
        System.out.println(sw1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Pickle pickle = new Pickle("Mango Pickle", 150);
        pickle.preserve();
        Pickle mango = new MangoPickle();
        mango.preserve();
        MangoPickle mangoPickle = new MangoPickle();
        mangoPickle.preserve();
        mangoPickle.taste();
        Castclass pik = new Castclass();
        pik.pick(pickle);
        pik.pick(mangoPickle);
        Pickle pickle1 = new Pickle("Mango Pickle", 150);
        pickle1.toString();
        System.out.println(pickle1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Tube tube = new Tube("Colgate", 90);
        tube.squeeze();
        Tube paste = new ToothpasteTube();
        paste.squeeze();
        ToothpasteTube toothpasteTube = new ToothpasteTube();
        toothpasteTube.squeeze();
        toothpasteTube.mintFlavor();
        Castclass past = new Castclass();
        past.tb(tube);
        past.tb(toothpasteTube);
        Tube tube1 = new Tube("Colgate", 90);
        tube1.toString();
        System.out.println(tube1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Blanket blanket = new Blanket("Wool", 1200);
        blanket.cover();
        Blanket wool = new WoolBlanket();
        wool.cover();
        WoolBlanket woolBlanket = new WoolBlanket();
        woolBlanket.cover();
        woolBlanket.warm();
        Castclass wol = new Castclass();
        wol.blank(blanket);
        wol.blank(woolBlanket);
        Blanket blanket1 = new Blanket("Wool", 1200);
        blanket1.toString();
        System.out.println(blanket1);

        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Stand stand = new Stand("Plastic", 250);
        stand.hold();
        Stand mobile3 = new MobileStand();
        mobile3.hold();
        MobileStand mobileStand = new MobileStand();
        mobileStand.hold();
        mobileStand.rotate();
        Castclass mob = new Castclass();
        mob.std(stand);
        mob.std(mobileStand);
        Stand stand1 = new Stand("Plastic", 250);
        stand1.toString();
        System.out.println(stand1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Bangle bangle = new Bangle("Silver", 2.2);
        bangle.wear();
        Bangle gold2 = new GoldBangle();
        gold2.wear();
        GoldBangle goldBangle = new GoldBangle();
        goldBangle.wear();
        goldBangle.sparkle();
        Castclass bgnl = new Castclass();
        bgnl.bgl(bangle);
        bgnl.bgl(goldBangle);
        Bangle bangle1 = new Bangle("Silver", 2.2);
        bangle1.toString();
        System.out.println(bangle1);

        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Mirror mirror = new Mirror("Rectangle", 800);
        mirror.reflect();
        Mirror wall = new WallMirror();
        wall.reflect();
        WallMirror wallMirror = new WallMirror();
        wallMirror.reflect();
        wallMirror.hang();
        Mirror mirror1 = new Mirror("Rectangle", 800);
        mirror1.toString();
        System.out.println(mirror1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Castclass mir = new Castclass();
        mir.mir(mirror);
        mir.mir(wallMirror);
        Elevator elevator = new Elevator("Schindler", 8);
        elevator.move();
        Elevator smart2 = new SmartElevator();
        smart2.move();
        SmartElevator smartElevator = new SmartElevator();
        smartElevator.move();
        Castclass ele = new Castclass();
        ele.eliv(elevator);
        ele.eliv(smartElevator);
        Elevator elevator1 = new Elevator("Schindler", 8);
        elevator1.toString();
        System.out.println(elevator1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Lamp lamp = new Lamp("LED", 1200);
        lamp.glow();
        Lamp table2 = new TableLamp();
        table2.glow();
        TableLamp tableLamp = new TableLamp();
        tableLamp.glow();
        tableLamp.adjust();
        Castclass lmp = new Castclass();
        lmp.lmp(lamp);
        lmp.lmp(tableLamp);
        Lamp lamp1 = new Lamp("LED", 1200);
        lamp1.toString();
        System.out.println(lamp1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Keychain keychain = new Keychain("Metal", 350);
        keychain.holdKeys();
        Keychain digital = new DigitalKeychain();
        digital.holdKeys();
        DigitalKeychain digitalKeychain = new DigitalKeychain();
        digitalKeychain.holdKeys();
        digitalKeychain.track();
        Castclass kchi = new Castclass();
        kchi.keych(keychain);
        kchi.keych(digitalKeychain);
        Keychain keychain1 = new Keychain("Metal", 350);
        keychain1.toString();
        System.out.println(keychain1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Keyboard keyboard = new Keyboard("Logitech", 4500);
        keyboard.type();
        Keyboard mechanical = new MechanicalKeyboard();
        mechanical.type();
        MechanicalKeyboard mechKeyboard = new MechanicalKeyboard();
        mechKeyboard.type();
        Castclass key = new Castclass();
        key.key(keyboard);
        key.key(mechKeyboard);
        Keyboard keyboard1 = new Keyboard("Logitech", 4500);
        keyboard1.toString();
        System.out.println(keyboard1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Trimmer trimmer = new Trimmer("Philips", 2500);
        trimmer.trim();
        Trimmer beard = new BeardTrimmer();
        beard.trim();
        BeardTrimmer beardTrimmer = new BeardTrimmer();
        beardTrimmer.trim();
        beardTrimmer.adjustLength();
        Castclass trimm = new Castclass();
        trimm.trm(trimmer);
        trimm.trm(beardTrimmer);
        Trimmer trimmer1 = new Trimmer("Philips", 2500);
        trimmer1.toString();
        System.out.println(trimmer1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Calendor calendor = new Calendor("Digital", 2025);
        calendor.showDate();
        Calendor digital2 = new DigitalCalendor();
        digital2.showDate();
        DigitalCalendor digitalCalendor = new DigitalCalendor();
        digitalCalendor.showDate();
        Castclass cal = new Castclass();
        cal.calend(calendor);
        cal.calend(digitalCalendor);
        Calendor calendor1 = new Calendor("Digital", 2025);
        calendor1.toString();
        System.out.println(calendor1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Spects spects = new Spects("Polarized", 1500);
        spects.wear();
        Spects sun2 = new SunGlasses();
        sun2.wear();
        SunGlasses sunGlasses = new SunGlasses();
        sunGlasses.wear();
        sunGlasses.blockSunlight();
        Castclass suny = new Castclass();
        suny.spect(spects);
        suny.spect(sunGlasses);
        Spects spects1 = new Spects("Polarized", 1500);
        spects1.toString();
        System.out.println(spects1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Book book = new Book("Digital Book", 300);
        book.read();
        Book ebook = new EBook();
        ebook.read();
        EBook myEBook = new EBook();
        myEBook.read();
        myEBook.download();
        Castclass red = new Castclass();
        red.arti(book);
        red.arti(ebook);
        Book book1 = new Book("Digital Book", 300);
        book1.toString();
        System.out.println(book1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Wallet wallet = new Wallet("PhonePe", 10000);
        wallet.carryCash();
        Wallet digital3 = new DigitalWallet();
        digital3.carryCash();
        DigitalWallet digitalWallet = new DigitalWallet();
        digitalWallet.carryCash();
        digitalWallet.scanQR();
        Castclass walt = new Castclass();
        walt.wlt(wallet);
        walt.wlt(digitalWallet);
        Wallet wallet1 = new Wallet("PhonePe", 10000);
        wallet1.toString();
        System.out.println(wallet1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Perfume perfume = new Perfume("Yardley", "Lavender");
        perfume.apply();
        Perfume spray = new BodySpray();
        spray.apply();
        BodySpray bodySpray = new BodySpray();
        bodySpray.apply();
        bodySpray.refresh();
        Castclass spry = new Castclass();
        spry.spry(perfume);
        spry.spry(bodySpray);
        Perfume perfume1 = new Perfume("Yardley", "Lavender");
        perfume1.toString();
        System.out.println(perfume1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Hammer hammer = new Hammer("Iron", 2.5);
        hammer.hit();
        Hammer sledge = new SledgeHammer();
        sledge.hit();
        SledgeHammer sledgeHammer = new SledgeHammer();
        sledgeHammer.hit();
        sledgeHammer.breakConcrete();
        Castclass hmr = new Castclass();
        hmr.ham(hammer);
        hmr.ham(sledgeHammer);
        Hammer hammer3 = new Hammer("Iron", 2.5);
        hammer3.toString();
        System.out.println(hammer3);
        System.out.println(hammer);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Charger charger = new Charger("Samsung", 25);
        charger.plugIn();
        Charger fast = new FastCharger();
        fast.plugIn();
        FastCharger fastCharger = new FastCharger();
        fastCharger.plugIn();
        fastCharger.quickCharge();
        Castclass chrg = new Castclass();
        chrg.charge(charger);
        chrg.charge(fastCharger);
        Charger charger1 = new Charger("Samsung", 25);
        charger1.toString();
        System.out.println(charger1);

        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Bat bat = new Bat("MRF", 1.3);
        bat.swing();
        Bat cricket = new CricketBat();
        cricket.swing();
        CricketBat cricketBat = new CricketBat();
        cricketBat.swing();
        cricketBat.hitBall();
        Castclass crtbt = new Castclass();
        crtbt.bit(bat);
        crtbt.bit(cricketBat);
        Bat bat1 = new Bat("MRF", 1.3);
        bat1.toString();
        System.out.println(bat1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Idol idol = new Idol("Marble", 4.0);
        idol.worship();
        Idol stone = new StoneIdol();
        stone.worship();
        StoneIdol stoneIdol = new StoneIdol();
        stoneIdol.worship();
        stoneIdol.polish();
        Castclass gri = new Castclass();
        gri.idl(idol);
        gri.idl(stoneIdol);
        Idol idol1 = new Idol("Marble", 4.0);
        idol1.toString();
        System.out.println(idol1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Chilli chilli = new Chilli("Red", 10);
        chilli.spiceUp();
        Chilli green = new GreenChilli();
        green.spiceUp();
        GreenChilli greenChilli = new GreenChilli();
        greenChilli.spiceUp();
        greenChilli.makePickle();
        Castclass chil = new Castclass();
        chil.green(chilli);
        chil.green(greenChilli);
        Chilli chilli1 = new Chilli("Red", 10);
        chilli1.toString();
        System.out.println(chilli1);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Milk milk = new Milk("Plain", 1.0);
        milk.drink();
        System.out.println(milk);
        FlavoredMilk flavoredMilk = new FlavoredMilk();
        flavoredMilk.drink();
        flavoredMilk.addFlavor();
        Castclass nandi=new Castclass();
        nandi.mlk(milk);
        nandi.mlk(flavoredMilk);
        Milk milk3 = new Milk("Plain", 1.0);
        milk3.toString();
        System.out.println(milk3);

        Dell dell = new Dell("Inspiron", 24.0);
        dell.dell();
        Dell dell1=new Monitor();
        dell1.dell();
        Monitor monitor = new Monitor();
        monitor.dell();
        monitor.display();
        Castclass moni=new Castclass();

        moni.dl(monitor);
        Dell dell3 = new Dell("Inspiron", 24.0);
        dell3.toString();
        System.out.println(dell3);

        Metro metro = new Metro("Green Line", 10);
        metro.travel();
        Metro metro1=new ExpressMetro();
        metro1.travel();
        ExpressMetro expressMetro=new ExpressMetro();
        expressMetro.speed();
        expressMetro.travel();
        Castclass metr=new Castclass();
        metr.rail(expressMetro);
        Metro metro2 = new Metro("Green Line", 10);
        metro2.toString();
        System.out.println(metro2);
        Chikmagalru chikmagalru = new Chikmagalru("Chikmagalur", 1090.0);
        Chikmagalru chikmagalru1=new Sakre();
        chikmagalru1.ckmgr();
        Sakre sakre=new Sakre();
        sakre.sakre();
        sakre.ckmgr();
        Castclass sugar=new Castclass();
        sugar.haven(chikmagalru1);
        sugar.haven(sakre);
        chikmagalru.ckmgr();
        Chikmagalru chikmagalru2 = new Chikmagalru("Chikmagalur", 1090.0);
        chikmagalru2.toString();
        System.out.println(chikmagalru2);
        System.out.println(chikmagalru);

    }

}



