package com.java.inherMtd.internal;

public class Runner {
    public static void main(String[] args) {
        HP hp=new HP();
        hp.pc();
        HP lp=new Laptop();
        lp.pc();
        Laptop laptop=new Laptop();
        laptop.pc();
        laptop.ram();
        Shirt shirt=new Shirt();
        shirt.clt();
        Shirt srt= new Pant();
        srt.clt();
        Pant pant=new Pant();
        pant.clt();
        pant.pt();
        Sun sun=new Sun();
        sun.slr();
        Sun sn=new Earth();
        sn.slr();
        Earth earth=new Earth();
        earth.lnd();
        earth.slr();
        Tree tree=new Tree();
        tree.tree();
        Tree tr=new Plant();
        tr.tree();
        Plant plant=new Plant();
        plant.plt();
        plant.tree();
        Pen pen=new Pen();
        pen.wrt();
        Pen pn=new Pencil();
        pn.wrt();
        Pencil pencil=new Pencil();
        pencil.pncl();
        pencil.wrt();
        Bedsheet bedsheet=new Bedsheet();
        bedsheet.bdst();
        Bedsheet bdt=new Pillow();
        bdt.bdst();
        Pillow pillow=new Pillow();
        pillow.pill();
        pillow.bdst();
        Alchol alchol=new Alchol();
        alchol.alc();
        Alchol alh=new Beer();
        alh.alc();
        Beer beer=new Beer();
        beer.alc();
        beer.ber();
        Samsung samsung=new Samsung();
        samsung.sam();
        Samsung smng=new Mobile();
        Mobile mobile=new Mobile();
        mobile.mbl();
        mobile.sam();
        Mac mac=new Mac();
        mac.Mc();;
        Mac mc=new Tab();
        mc.Mc();
        Tab tab=new Tab();
        tab.Mc();
        tab.tab();
        Rocket rocket=new Rocket();
        rocket.rct();
        Rocket rct=new Sattelite();
        rct.rct();
        Sattelite sattelite=new Sattelite();
        sattelite.rct();
        sattelite.stlt();
        Bird bird=new Bird();
        bird.brd();
        Bird bid=new Eagle();
        bid.brd();
        Eagle eagle=new Eagle();
        eagle.brd();
        eagle.egle();
        Flover flover=new Flover();
        flover.flr();
        Flover fvr= new Rose();
        fvr.flr();
        Rose rose=new Rose();
        rose.flr();
        rose.rse();
        Navagraha navagraha=new Navagraha();
        navagraha.nava();
        Navagraha nvg=new Darshan();
        nvg.nava();
        Darshan darshan=new Darshan();
        darshan.darshu();
        darshan.nava();
        Bottle bottle=new Bottle();
        bottle.btl();
        Bottle btl=new Glass();
        btl.btl();
        Glass glass=new Glass();
        glass.gls();
        glass.btl();
        Seed seed=new Seed();
        seed.sed();
        Seed sd=new Friut();
        Friut friut=new Friut();
        friut.frt();
        friut.sed();
        Sudeep sudeep=new Sudeep();
        sudeep.sude();
        Sudeep sup=new MAX();
        sup.sude();
        MAX max=new MAX();
        max.mx();
        max.sude();
        Ore ore=new Ore();
        ore.ore();
        Ore or=new Iron();
        or.ore();
        Iron irn=new Iron();
        irn.iron();
        irn.ore();
        Bed bed=new Bed();
        bed.bed();
        Bed bd=new Foam();
        bd.bed();
        Foam foam=new Foam();
        foam.bed();
        foam.foam();
        LG lg=new LG();
        lg.lg();
        LG lg1=new Fridge();
        lg1.lg();
        Fridge fridge=new Fridge();
        fridge.fridge();
        fridge.lg();
        IFB ifb=new IFB();
        ifb.wash();
        IFB ifb1=new Washingmch();
        ifb1.wash();
        Washingmch washingmch=new Washingmch();
        washingmch.mch();
        washingmch.wash();
        Voltas voltas=new Voltas();
        voltas.vlts();
        Voltas vlt= new AC();
        vlt.vlts();
        AC ac=new AC();
        ac.Aircool();
        ac.vlts();
        Door door=new Door();
        door.dor();
        Door dor=new Window();
        dor.dor();
        Window window=new Window();
        window.dor();;
        window.Windo();
        Billagate billagate=new Billagate();
        billagate.bill();
        Billagate bil =new Micro();
        bil.bill();
        Micro micro=new Micro();
        micro.micro();
        micro.bill();
        Skybag skybag=new Skybag();
        skybag.sky();
        Skybag bag=new Bag();
        bag.sky();
        Bag bag1=new Bag();
        bag1.bag();
        bag1.sky();
        Fruit fruit=new Fruit();
        fruit.fruit();
        Fruit frt=new Apple();
        frt.fruit();
        Apple apple=new Apple();
        apple.apple();
        apple.fruit();
        Ganesh ganesh=new Ganesh();
        ganesh.gani();
        Ganesh gani=new Zoom();
        Zoom zoom=new Zoom();
        zoom.gani();
        zoom.zoom();
        Hair hair=new Hair();
        hair.hair();
        Hair hir=new Band();
        hir.hair();
        Band band=new Band();
        band.band();
        band.hair();
        Oven oven=new Oven();
        oven.oven();
        Oven ovn=new Heat();
        ovn.oven();
        Heat heat=new Heat();
        heat.heat();
        heat.oven();
        Gun gun=new Gun();
        gun.gun();
        Gun gn=new MP5();
        gn.gun();
        MP5 mp5=new MP5();
        mp5.gun();
        mp5.mp();
        India india=new India();
        india.india();
        India indi=new Delhi();
        indi.india();
        Delhi delhi=new Delhi();
        delhi.delhi();
        delhi.india();
        Paper paper=new Paper();
        paper.paper();
        Paper ppr=new A4();
        ppr.paper();
        A4 a4=new A4();
        a4.appr();
        a4.paper();
        Honda honda=new Honda();
        honda.honda();
        Honda hond=new Civic();
        hond.honda();
        Civic civic=new Civic();
        civic.civic();
        civic.honda();
        Suzuki suzuki=new Suzuki();
        suzuki.suzuki();
        Suzuki suzu=new Swift();
        suzu.suzuki();
        Swift swift=new Swift();
        swift.swift();
        suzu.suzuki();
        Yamaha yamaha=new Yamaha();
        yamaha.yamaha();
        Yamaha yamaha1=new RX();
        yamaha.yamaha();
        RX rx=new RX();
        rx.rx();
        rx.yamaha();
        TVS tvs=new TVS();
        tvs.tvs();
        TVS tvs1=new Jpiter();
        tvs1.tvs();
        Jpiter jpiter=new Jpiter();
        jpiter.Jpter();
        jpiter.tvs();
        Hero hero=new Hero();
        hero.hero();
        Hero hero1=new Cdh();
        hero1.hero();;
        Cdh cdh=new Cdh();
        cdh.cdh();
        cdh.hero();
        JCB jcb=new JCB();
        jcb.jcb();
        JCB jcb1=new Hita();
        jcb1.jcb();
        Hita hita=new Hita();
        hita.hita();
        hita.jcb();
        RCB rcb=new RCB();
        rcb.rcb();
        RCB rcb1=new Virat();
        rcb1.rcb();
        Virat virat=new Virat();
        virat.rcb();
        virat.virat();
        Karnataka karnataka=new Karnataka();
        karnataka.state();
        Karnataka karnataka1=new Benlore();
        karnataka.state();
        Benlore benlore=new Benlore();
        benlore.bnglr();
        benlore.state();
        Water water=new Water();
        water.water();;
        Water water1=new Fish();
        water1.water();
        Fish fish=new Fish();
        fish.fish();
        fish.water();
        Brain brain=new Brain();
        brain.brain();
        Brain brain1=new Nueral();
        brain1.brain();
        Nueral nueral=new Nueral();
        nueral.brain();
        nueral.nuerl();
        CPU cpu=new CPU();
        cpu.cpu();
        CPU cpu1=new Procces();
        cpu1.cpu();
        Procces procces=new Procces();
        procces.cpu();
        procces.Proces();
        Parle parle=new Parle();
        parle.parle();
        Parle parle1=new G();
        parle1.parle();
        G g=new G();
        g.G();
        g.parle();
        Mari mari=new Mari();
        mari.mari();
        Mari mari1=new Lite();
        mari1.mari();
        Lite lite=new Lite();
        lite.lite();
        lite.mari();
        Chrdurga chrdurga=new Chrdurga();
        chrdurga.ctd();
        Chrdurga chrdurga1=new Chrdurga();
        chrdurga1.ctd();
        Clk clk=new Clk();
        clk.clk();
        clk.ctd();
        Davanagere davanagere=new Davanagere();
        davanagere.dvg();
        Davanagere davanagere1=new Harihar();
        davanagere1.dvg();
        Harihar harihar=new Harihar();
        harihar.dvg();
        harihar.hari();
        Thumkur thumkur=new Thumkur();
        thumkur.tmkr();
        Thumkur thumkur1=new Pavgada();
        thumkur1.tmkr();
        Pavgada pavgada=new Pavgada();
        pavgada.pvgd();
        pavgada.tmkr();
        Shivmoga shivmoga=new Shivmoga();
        shivmoga.shmg();
        Shivmoga shivmoga1=new Sagara();
        shivmoga1.shmg();
        Sagara sagara=new Sagara();
        sagara.sagara();
        sagara.shmg();
        Java java=new Java();
        java.jva();
        Java java1=new Jvm();
        java1.jva();
        Jvm jvm=new Jvm();
        jvm.jva();
        jvm.jva();
        Romeo romeo=new Romeo();
        romeo.romeo();
        Romeo romeo1=new Romeo();
        romeo1.romeo();
        Juleat juleat=new Juleat();
        juleat.juleat();
        juleat.juleat();
        Wifi wifi=new Wifi();
        wifi.wifi();
        Wifi wifi1=new Hotspot();
        wifi1.wifi();
        Hotspot hotspot=new Hotspot();
        hotspot.hotspot();
        Lion lion=new Lion();
        lion.lion();
        Lion lion1=new Cat();
        lion1.lion();
        Cat cat=new Cat();
        Table table = new Table();
        table.furniture();
        Table wt = new WoodenTable();
        wt.furniture();
        WoodenTable woodenTable = new WoodenTable();
        woodenTable.furniture();
        woodenTable.polish();
        Towel towel = new Towel();
        towel.cloth();
        Towel bt = new BathTowel();
        bt.cloth();
        BathTowel bathTowel = new BathTowel();
        bathTowel.cloth();
        bathTowel.absorb();
        Curtain curtain = new Curtain();
        curtain.fabric();
        Curtain wc = new WindowCurtain();
        wc.fabric();
        WindowCurtain windowCurtain = new WindowCurtain();
        windowCurtain.fabric();
        windowCurtain.cover();
        Truck truck = new Truck();
        truck.load();
        Truck mt = new MiniTruck();
        mt.load();
        MiniTruck miniTruck = new MiniTruck();
        miniTruck.load();
        miniTruck.capacity();
        IronBox ironBox = new IronBox();
        ironBox.heat();
        IronBox si = new SteamIron();
        si.heat();
        SteamIron steamIron = new SteamIron();
        steamIron.heat();
        steamIron.steam();
        Missile missile = new Missile();
        missile.launch();
        Missile gm = new GuidedMissile();
        gm.launch();
        GuidedMissile guidedMissile = new GuidedMissile();
        guidedMissile.launch();
        guidedMissile.target();
        Land land = new Land();
        land.property();
        Land agLand = new AgriLand();
        agLand.property();
        AgriLand agriculturalLand = new AgriLand();
        agriculturalLand.property();
        agriculturalLand.cultivate();
        Ragi ragi=new Ragi();
        ragi.grain();
        Ragi ragi1=new Ragi();
        ragi1.grain();
        RagiMalt ragiMalt=new RagiMalt();
        ragiMalt.drink();
        ragiMalt.grain();
        GoldChain gold = new GoldChain();
        gold.shine();
        GoldChain fancy = new Gold();
        fancy.shine();
        Gold fancyGold = new Gold();
        fancyGold.shine();
        fancyGold.design();
        Battery battery = new Battery();
        battery.power();
        Battery rb = new Exide();
        rb.power();
        Exide rechargeableBattery = new Exide();
        rechargeableBattery.power();
        rechargeableBattery.charge();
        Tank tank = new Tank();
        tank.fire();
        Tank bttl = new BattleTank();
        bttl.fire();
        BattleTank battleTank = new BattleTank();
        battleTank.fire();
        battleTank.armor();
        Bow bow = new Bow();
        bow.shoot();
        Bow lb = new LongBow();
        lb.shoot();
        LongBow longBow = new LongBow();
        longBow.shoot();
        longBow.range();
        Bowl bowl = new Bowl();
        bowl.hold();
        Bowl sb = new SoupBowl();
        sb.hold();
        SoupBowl soupBowl = new SoupBowl();
        soupBowl.hold();
        soupBowl.serve();
        Rice rice = new Rice();
        rice.cook();
        Rice basmati = new BasmatiRice();
        basmati.cook();
        BasmatiRice basmatiRice = new BasmatiRice();
        basmatiRice.cook();
        basmatiRice.aroma();
        BislariBottle bottle2 = new BislariBottle();
        bottle2.fill();
        BislariBottle wb = new WaterBottle();
        wb.fill();
        WaterBottle waterBottle = new WaterBottle();
        waterBottle.fill();
        waterBottle.drink();
        Printer printer = new Printer();
        printer.print();
        Printer lp1 = new LaserPrinter();
        lp1.print();
        LaserPrinter laserPrinter = new LaserPrinter();
        laserPrinter.print();
        laserPrinter.speed();
        Kurtha kurtha = new Kurtha();
        kurtha.wear();
        Kurtha designer = new DesiKurtha();
        designer.wear();
        DesiKurtha designerKurtha = new DesiKurtha();
        designerKurtha.wear();
        designerKurtha.embroidery();
        Xerox xerox = new Xerox();
        xerox.copy();
        Xerox color = new ColorXerox();
        color.copy();
        ColorXerox colorXerox = new ColorXerox();
        colorXerox.copy();
        Train train = new Train();
        train.move();
        Train bullet = new BulletTrain();
        bullet.move();
        BulletTrain bulletTrain = new BulletTrain();
        bulletTrain.move();
        bulletTrain.highSpeed();
        Spoon spoon = new Spoon();
        spoon.scoop();
        Spoon silver = new SilverSpoon();
        silver.scoop();
        SilverSpoon silverSpoon = new SilverSpoon();
        silverSpoon.scoop();
        silverSpoon.shine();
        Fork fork = new Fork();
        fork.pick();
        Fork salad = new SaladFork();
        salad.pick();
        SaladFork saladFork = new SaladFork();
        saladFork.pick();
        saladFork.grip();
        Film film = new Film();
        film.play();
        Film doc = new DocumentaryFilm();
        doc.play();
        DocumentaryFilm documentary = new DocumentaryFilm();
        documentary.play();
        documentary.educate();
        Switch sw = new Switch();
        sw.turnOn();
        Switch smart = new SmartSwitch();
        smart.turnOn();
        SmartSwitch smartSwitch = new SmartSwitch();
        smartSwitch.turnOn();
        smartSwitch.schedule();
        Pickle pickle = new Pickle();
        pickle.preserve();
        Pickle mango = new MangoPickle();
        mango.preserve();
        MangoPickle mangoPickle = new MangoPickle();
        mangoPickle.preserve();
        mangoPickle.taste();
        Tube tube = new Tube();
        tube.squeeze();
        Tube paste = new ToothpasteTube();
        paste.squeeze();
        ToothpasteTube toothpasteTube = new ToothpasteTube();
        toothpasteTube.squeeze();
        toothpasteTube.mintFlavor();
        Blanket blanket = new Blanket();
        blanket.cover();
        Blanket wool = new WoolBlanket();
        wool.cover();
        WoolBlanket woolBlanket = new WoolBlanket();
        woolBlanket.cover();
        woolBlanket.warm();
        Stand stand = new Stand();
        stand.hold();
        Stand mobile3 = new MobileStand();
        mobile3.hold();
        MobileStand mobileStand = new MobileStand();
        mobileStand.hold();
        Bangle bangle = new Bangle();
        bangle.wear();
        Bangle gold2 = new GoldBangle();
        gold2.wear();
        GoldBangle goldBangle = new GoldBangle();
        goldBangle.wear();
        goldBangle.sparkle();
        Mirror mirror = new Mirror();
        mirror.reflect();
        Mirror wall = new WallMirror();
        wall.reflect();
        WallMirror wallMirror = new WallMirror();
        wallMirror.reflect();
        wallMirror.hang();
        Elevator elevator = new Elevator();
        elevator.move();
        Elevator smart2 = new SmartElevator();
        smart2.move();
        SmartElevator smartElevator = new SmartElevator();
        smartElevator.move();
        Lamp lamp = new Lamp();
        lamp.glow();
        Lamp table2 = new TableLamp();
        table2.glow();
        TableLamp tableLamp = new TableLamp();
        tableLamp.glow();
        tableLamp.adjust();
        Keychain keychain = new Keychain();
        keychain.holdKeys();
        Keychain digital = new DigitalKeychain();
        digital.holdKeys();
        DigitalKeychain digitalKeychain = new DigitalKeychain();
        digitalKeychain.holdKeys();
        Keyboard keyboard = new Keyboard();
        keyboard.type();
        Keyboard mechanical = new MechanicalKeyboard();
        mechanical.type();
        MechanicalKeyboard mechKeyboard = new MechanicalKeyboard();
        mechKeyboard.type();
        Trimmer trimmer = new Trimmer();
        trimmer.trim();
        Trimmer beard = new BeardTrimmer();
        beard.trim();
        BeardTrimmer beardTrimmer = new BeardTrimmer();
        beardTrimmer.trim();
        beardTrimmer.adjustLength();
        Calendor calendor = new Calendor();
        calendor.showDate();
        Calendor digital2 = new DigitalCalendor();
        digital2.showDate();
        DigitalCalendor digitalCalendor = new DigitalCalendor();
        digitalCalendor.showDate();
        Spects spects = new Spects();
        spects.wear();
        Spects sun2 = new SunGlasses();
        sun2.wear();
        SunGlasses sunGlasses = new SunGlasses();
        sunGlasses.wear();
        sunGlasses.blockSunlight();
        Book book = new Book();
        book.read();
        Book ebook = new EBook();
        ebook.read();
        EBook myEBook = new EBook();
        myEBook.read();
        myEBook.download();
        Wallet wallet = new Wallet();
        wallet.carryCash();
        Wallet digital3 = new DigitalWallet();
        digital3.carryCash();
        DigitalWallet digitalWallet = new DigitalWallet();
        digitalWallet.carryCash();
        digitalWallet.scanQR();
        Perfume perfume = new Perfume();
        perfume.apply();
        Perfume spray = new BodySpray();
        spray.apply();
        BodySpray bodySpray = new BodySpray();
        bodySpray.apply();
        bodySpray.refresh();
        Hammer hammer = new Hammer();
        hammer.hit();
        Hammer sledge = new SledgeHammer();
        sledge.hit();
        SledgeHammer sledgeHammer = new SledgeHammer();
        sledgeHammer.hit();
        sledgeHammer.breakConcrete();
        Charger charger = new Charger();
        charger.plugIn();
        Charger fast = new FastCharger();
        fast.plugIn();
        FastCharger fastCharger = new FastCharger();
        fastCharger.plugIn();
        fastCharger.quickCharge();
        Bat bat = new Bat();
        bat.swing();
        Bat cricket = new CricketBat();
        cricket.swing();
        CricketBat cricketBat = new CricketBat();
        cricketBat.swing();
        cricketBat.hitBall();
        Idol idol = new Idol();
        idol.worship();
        Idol stone = new StoneIdol();
        stone.worship();
        StoneIdol stoneIdol = new StoneIdol();
        stoneIdol.worship();
        stoneIdol.polish();
        Chilli chilli = new Chilli();
        chilli.spiceUp();
        Chilli green = new GreenChilli();
        green.spiceUp();
        GreenChilli greenChilli = new GreenChilli();
        greenChilli.spiceUp();
        greenChilli.makePickle();







    }
}
