package com.java.inherMtd.internal;

public class Runner {
    public static void main(String[] args) {
        HP hp=new HP();
        hp.pc();
        HP lp=new Laptop();
        lp.pc();
        Laptop laptop=new Laptop();
        laptop.pc();
        laptop.ram();
        Castclass castclass=new Castclass();
        castclass.hpz(hp);
        castclass.hpz(lp);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Shirt shirt=new Shirt();
        shirt.clt();
        Shirt srt= new Pant();
        srt.clt();
        Pant pant=new Pant();
        pant.clt();
        pant.pt();
        Castclass leni=new Castclass();
        leni.lenin(srt);
        leni.lenin(pant);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Sun sun=new Sun();
        sun.slr();
        Sun sn=new Earth();
        sn.slr();
        Earth earth=new Earth();
        earth.lnd();
        earth.slr();
        Castclass erth=new Castclass();
        erth.hpz(sn);
        erth.hpz(earth);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Tree tree=new Tree();
        tree.tree();
        Tree tr=new Plant();
        tr.tree();
        Plant plant=new Plant();
        plant.plt();
        plant.tree();
        Castclass pln=new Castclass();
        pln.tre(tree);
        pln.tre(plant);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Pen pen=new Pen();
        pen.wrt();
        Pen pn=new Pencil();
        pn.wrt();
        Pencil pencil=new Pencil();
        pencil.pncl();
        pencil.wrt();
        Castclass cil=new Castclass();
        cil.pen(pen);
        cil.pen(pencil);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Bedsheet bedsheet=new Bedsheet();
        bedsheet.bdst();
        Bedsheet bdt=new Pillow();
        bdt.bdst();
        Pillow pillow=new Pillow();
        pillow.pill();
        pillow.bdst();
        Castclass shet=new Castclass();
        shet.bed(bedsheet);
        shet.bed(pillow);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Alchol alchol=new Alchol();
        alchol.alc();
        Alchol alh=new Beer();
        alh.alc();
        Beer beer=new Beer();
        beer.alc();
        beer.ber();
        Castclass alch=new Castclass();
        alch.alco(alchol);
        alch.alco(beer);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Samsung samsung=new Samsung();
        samsung.sam();
        Samsung smng=new Mobile();
        Mobile mobile=new Mobile();
        mobile.mbl();
        mobile.sam();
        Castclass sam=new Castclass();
        sam.sug(samsung);
        sam.sug(mobile);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Mac mac=new Mac();
        mac.Mc();;
        Mac mc=new Tab();
        mc.Mc();
        Tab tab=new Tab();
        tab.Mc();
        tab.tab();
        Castclass macc=new Castclass();
        macc.mc(mac);
        macc.mc(tab);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Rocket rocket=new Rocket();
        rocket.rct();
        Rocket rct=new Sattelite();
        rct.rct();
        Sattelite sattelite=new Sattelite();
        sattelite.rct();
        sattelite.stlt();
        Castclass rock=new Castclass();
        rock.roc(rocket);
        rock.roc(sattelite);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Bird bird=new Bird();
        bird.brd();
        Bird bid=new Eagle();
        bid.brd();
        Eagle eagle=new Eagle();
        eagle.brd();
        eagle.egle();
        Castclass kiw=new Castclass();
        kiw.brd(bid);
        kiw.brd(eagle);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Flover flover=new Flover();
        flover.flr();
        Flover fvr= new Rose();
        fvr.flr();
        Rose rose=new Rose();
        rose.flr();
        rose.rse();
        Castclass rse=new Castclass();
        rse.flower(flover);
        rse.flower(rose);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Navagraha navagraha=new Navagraha();
        navagraha.nava();
        Navagraha nvg=new Darshan();
        nvg.nava();
        Darshan darshan=new Darshan();
        darshan.darshu();
        darshan.nava();
        Castclass dasa=new Castclass();
        dasa.nava(navagraha);
        dasa.nava(darshan);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Bottle bottle=new Bottle();
        bottle.btl();
        Bottle btl=new Glass();
        btl.btl();
        Glass glass=new Glass();
        glass.gls();
        glass.btl();
        Castclass kln=new Castclass();
        kln.Btl(bottle);
        kln.Btl(glass);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Seed seed=new Seed();
        seed.sed();
        Seed sd=new Friut();
        Friut friut=new Friut();
        friut.frt();
        friut.sed();
        Castclass frut=new Castclass();
        frut.nut(friut);
        frut.nut(seed);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Sudeep sudeep=new Sudeep();
        sudeep.sude();
        Sudeep sup=new MAX();
        sup.sude();
        MAX max=new MAX();
        max.mx();
        max.sude();
        Castclass sdp=new Castclass();
        sdp.sudee(sup);
        sdp.sudee(max);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Ore ore=new Ore();
        ore.ore();
        Ore or=new Iron();
        or.ore();
        Iron irn=new Iron();
        irn.iron();
        irn.ore();
        Castclass iron=new Castclass();
        iron.mgn(ore);
        iron.mgn(irn);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Bed bed=new Bed();
        bed.bed();
        Bed bd=new Foam();
        bd.bed();
        Foam foam=new Foam();
        foam.bed();
        foam.foam();
        Castclass fm=new Castclass();
        fm.soft(bd);
        fm.soft(foam);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        LG lg=new LG();
        lg.lg();
        LG lg1=new Fridge();
        lg1.lg();
        Fridge fridge=new Fridge();
        fridge.fridge();
        fridge.lg();
        Castclass frg=new Castclass();
        frg.frige(lg);
        frg.frige(fridge);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        IFB ifb=new IFB();
        ifb.wash();
        IFB ifb1=new Washingmch();
        ifb1.wash();
        Washingmch washingmch=new Washingmch();
        washingmch.mch();
        washingmch.wash();
        Castclass wasn =new Castclass();
        wasn.mchn(ifb);
        wasn.mchn(washingmch);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Voltas voltas=new Voltas();
        voltas.vlts();
        Voltas vlt= new AC();
        vlt.vlts();
        AC ac=new AC();
        ac.Aircool();
        ac.vlts();
        Castclass cool=new Castclass();
        cool.volt(vlt);
        cool.volt(ac);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Door door=new Door();
        door.dor();
        Door dor=new Window();
        dor.dor();
        Window window=new Window();
        window.dor();;
        window.Windo();
        Castclass dr=new Castclass();
        dr.sefe(door);
        dr.sefe(window);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Billagate billagate=new Billagate();
        billagate.bill();
        Billagate bil =new Micro();
        bil.bill();
        Micro micro=new Micro();
        micro.micro();
        micro.bill();
        Castclass gate=new Castclass();
        gate.gates(billagate);
        gate.gates(micro);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Skybag skybag=new Skybag();
        skybag.sky();
        Skybag bag=new Bag();
        bag.sky();
        Bag bag1=new Bag();
        bag1.bag();
        bag1.sky();
        Castclass bg=new Castclass();
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        bg.sky(skybag);
        bg.sky(bag);
        Fruit fruit=new Fruit();
        fruit.fruit();
        Fruit frt=new Apple();
        frt.fruit();
        Apple apple=new Apple();
        apple.apple();
        apple.fruit();
        Castclass frit=new Castclass();
        frit.frut(fruit);
        frit.frut(apple);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Ganesh ganesh=new Ganesh();
        ganesh.gani();
        Ganesh gani=new Zoom();
        Zoom zoom=new Zoom();
        zoom.gani();
        zoom.zoom();
        Castclass gan=new Castclass();
        gan.gani(ganesh);
        gan.gani(zoom);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Hair hair=new Hair();
        hair.hair();
        Hair hir=new Band();
        hir.hair();
        Band band=new Band();
        band.band();
        band.hair();
        Castclass smp=new Castclass();
        smp.samp(hir);
        smp.samp(band);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Oven oven=new Oven();
        oven.oven();
        Oven ovn=new Heat();
        ovn.oven();
        Heat heat=new Heat();
        heat.heat();
        heat.oven();
        Castclass ht=new Castclass();
        ht.ovn(ovn);
        ht.ovn(heat);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Gun gun=new Gun();
        gun.gun();
        Gun gn=new MP5();
        gn.gun();
        MP5 mp5=new MP5();
        mp5.gun();
        mp5.mp();
        Castclass rfl=new Castclass();
        rfl.Rifl(gun);
        rfl.Rifl(mp5);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        India india=new India();
        india.india();
        India indi=new Delhi();
        indi.india();
        Delhi delhi=new Delhi();
        delhi.delhi();
        delhi.india();
        Castclass deli= new Castclass();
        deli.indus(india);
        deli.indus(delhi);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Paper paper=new Paper();
        paper.paper();
        Paper ppr=new A4();
        ppr.paper();
        A4 a4=new A4();
        a4.appr();
        a4.paper();
        Castclass pap=new Castclass();
        pap.buff(paper);
        pap.buff(a4);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Honda honda=new Honda();
        honda.honda();
        Honda hond=new Civic();
        hond.honda();
        Civic civic=new Civic();
        civic.civic();
        civic.honda();
        Castclass hon=new Castclass();
        hon.hond(hond);
        hon.hond(civic);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Suzuki suzuki=new Suzuki();
        suzuki.suzuki();
        Suzuki suzu=new Swift();
        suzu.suzuki();
        Swift swift=new Swift();
        swift.swift();
        swift.suzuki();
        Castclass swif=new Castclass();
        swif.suzu(suzuki);
        swif.suzu(swift);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Yamaha yamaha=new Yamaha();
        yamaha.yamaha();
        Yamaha yamaha1=new RX();
        yamaha.yamaha();
        RX rx=new RX();
        rx.rx();
        rx.yamaha();
        Castclass yam=new Castclass();
        yam.yamah(yamaha);
        yam.yamah(rx);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        TVS tvs=new TVS();
        tvs.tvs();
        TVS tvs1=new Jpiter();
        tvs1.tvs();
        Jpiter jpiter=new Jpiter();
        jpiter.Jpter();
        jpiter.tvs();
        Castclass ap=new Castclass();
        ap.tvs(tvs);
        ap.tvs(jpiter);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Hero hero=new Hero();
        hero.hero();
        Hero hero1=new Cdh();
        hero1.hero();
        Cdh cdh=new Cdh();
        cdh.cdh();
        cdh.hero();
        Castclass her=new Castclass();
        her.hero(hero1);
        her.hero(cdh);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        JCB jcb=new JCB();
        jcb.jcb();
        JCB jcb1=new Hita();
        jcb1.jcb();
        Hita hita=new Hita();
        hita.hita();
        hita.jcb();
        Castclass hit=new Castclass();
        hit.jcb(jcb);
        hit.jcb(hita);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        RCB rcb=new RCB();
        rcb.rcb();
        RCB rcb1=new Virat();
        rcb1.rcb();
        Virat virat=new Virat();
        virat.rcb();
        virat.virat();
        Castclass rc=new Castclass();
        rc.bang(rcb);
        rc.bang(virat);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Karnataka karnataka=new Karnataka();
        karnataka.state();
        Karnataka karnataka1=new Benlore();
        karnataka.state();
        Benlore benlore=new Benlore();
        benlore.bnglr();
        benlore.state();
        Castclass kar=new Castclass();
        kar.karu(karnataka);
        kar.karu(benlore);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Water water=new Water();
        water.water();;
        Water water1=new Fish();
        water1.water();
        Fish fish=new Fish();
        fish.fish();
        fish.water();
        Castclass min=new Castclass();
        min.neer(water);
        min.neer(fish);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Brain brain=new Brain();
        brain.brain();
        Brain brain1=new Nueral();
        brain1.brain();
        Nueral nueral=new Nueral();
        nueral.brain();
        nueral.nuerl();
        Castclass neu=new Castclass();
        neu.ment(brain);
        neu.ment(nueral);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        CPU cpu=new CPU();
        cpu.cpu();
        CPU cpu1=new Procces();
        cpu1.cpu();
        Procces procces=new Procces();
        procces.cpu();
        procces.Proces();
        Castclass cp=new Castclass();
        cp.proces(cpu);
        cp.proces(procces);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Parle parle=new Parle();
        parle.parle();
        Parle parle1=new G();
        parle1.parle();
        G g=new G();
        g.G();
        g.parle();
        Castclass par=new Castclass();
        par.par(parle);
        par.par(g);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Mari mari=new Mari();
        mari.mari();
        Mari mari1=new Lite();
        mari1.mari();
        Lite lite=new Lite();
        lite.lite();
        lite.mari();
        Castclass mar=new Castclass();
        mar.maru(mari);
        mar.maru(lite);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Chrdurga chrdurga=new Chrdurga();
        chrdurga.ctd();
        Chrdurga chrdurga1=new Chrdurga();
        chrdurga1.ctd();
        Clk clk=new Clk();
        clk.clk();
        clk.ctd();
        Castclass cld=new Castclass();
        cld.durga(chrdurga);
        cld.durga(clk);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Davanagere davanagere=new Davanagere();
        davanagere.dvg();
        Davanagere davanagere1=new Harihar();
        davanagere1.dvg();
        Harihar harihar=new Harihar();
        harihar.dvg();
        harihar.hari();
        Castclass hara=new Castclass();
        hara.davn(davanagere);
        hara.davn(harihar);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Thumkur thumkur=new Thumkur();
        thumkur.tmkr();
        Thumkur thumkur1=new Pavgada();
        thumkur1.tmkr();
        Pavgada pavgada=new Pavgada();
        pavgada.pvgd();
        pavgada.tmkr();
        Castclass pava=new Castclass();
        pava.tmkr(thumkur);
        pava.tmkr(pavgada);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Shivmoga shivmoga=new Shivmoga();
        shivmoga.shmg();
        Shivmoga shivmoga1=new Sagara();
        shivmoga1.shmg();
        Sagara sagara=new Sagara();
        sagara.sagara();
        sagara.shmg();
        Castclass sag=new Castclass();
        sag.shiv(shivmoga);
        sag.shiv(sagara);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Java java=new Java();
        java.jva();
        Java java1=new Jvm();
        java1.jva();
        Jvm jvm=new Jvm();
        jvm.jva();
        jvm.jva();
        Castclass ja=new Castclass();
        ja.jdk(java);
        ja.jdk(jvm);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Romeo romeo=new Romeo();
        romeo.romeo();
        Romeo romeo1=new Romeo();
        romeo1.romeo();
        Juleat juleat=new Juleat();
        juleat.juleat();
        juleat.juleat();
        Castclass jlt=new Castclass();
        jlt.rom(romeo);
        jlt.rom(juleat);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Wifi wifi=new Wifi();
        wifi.wifi();
        Wifi wifi1=new Hotspot();
        wifi1.wifi();
        Hotspot hotspot=new Hotspot();
        hotspot.hotspot();
        Castclass wfi=new Castclass();
        wfi.wi(wifi);
        wfi.wi(hotspot);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Lion lion=new Lion();
        lion.lion();
        Lion lion1=new Cat();
        lion1.lion();
        Cat cat=new Cat();
        Castclass lio=new Castclass();
        lio.leo(lion);
        lio.leo(cat);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Table table = new Table();
        table.furniture();
        Table wt = new WoodenTable();
        wt.furniture();
        WoodenTable woodenTable = new WoodenTable();
        woodenTable.furniture();
        woodenTable.polish();
        Castclass tbl=new Castclass();
        tbl.furn(table);
        tbl.furn(woodenTable);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Towel towel = new Towel();
        towel.cloth();
        Towel bt = new BathTowel();
        bt.cloth();
        BathTowel bathTowel = new BathTowel();
        bathTowel.cloth();
        bathTowel.absorb();
        Castclass tvl=new Castclass();
        tvl.tovel(towel);
        tvl.tovel(bathTowel);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Curtain curtain = new Curtain();
        curtain.fabric();
        Curtain wc = new WindowCurtain();
        wc.fabric();
        WindowCurtain windowCurtain = new WindowCurtain();
        windowCurtain.fabric();
        windowCurtain.cover();
        Castclass crt=new Castclass();
        crt.curt(curtain);
        crt.curt(windowCurtain);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Truck truck = new Truck();
        truck.load();
        Truck mt = new MiniTruck();
        mt.load();
        MiniTruck miniTruck = new MiniTruck();
        miniTruck.load();
        miniTruck.capacity();
        Castclass tck=new Castclass();
        tck.truk(truck);
        tck.truk(miniTruck);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        IronBox ironBox = new IronBox();
        ironBox.heat();
        IronBox si = new SteamIron();
        si.heat();
        SteamIron steamIron = new SteamIron();
        steamIron.heat();
        steamIron.steam();
        Castclass irnx=new Castclass();
        irnx.irnbx(ironBox);
        irnx.irnbx(steamIron);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Missile missile = new Missile();
        missile.launch();
        Missile gm = new GuidedMissile();
        gm.launch();
        GuidedMissile guidedMissile = new GuidedMissile();
        guidedMissile.launch();
        guidedMissile.target();
        Castclass miss=new Castclass();
        miss.misle(missile);
        miss.misle(guidedMissile);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Land land = new Land();
        land.property();
        Land agLand = new AgriLand();
        agLand.property();
        AgriLand agriculturalLand = new AgriLand();
        agriculturalLand.property();
        agriculturalLand.cultivate();
        Castclass ld=new Castclass();
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        ld.lnd(land);
        ld.lnd(agriculturalLand);
        Ragi ragi=new Ragi();
        ragi.grain();
        Ragi ragi1=new Ragi();
        ragi1.grain();
        RagiMalt ragiMalt=new RagiMalt();
        ragiMalt.drink();
        ragiMalt.grain();
        Castclass rg=new Castclass();
        rg.rag(ragi);
        rg.rag(ragiMalt);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        GoldChain gold = new GoldChain();
        gold.shine();
        GoldChain fancy = new Gold();
        fancy.shine();
        Gold fancyGold = new Gold();
        fancyGold.shine();
        fancyGold.design();
        Castclass gd=new Castclass();
        gd.goldch(gold);
        gd.goldch(fancyGold);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Battery battery = new Battery();
        battery.power();
        Battery rb = new Exide();
        rb.power();
        Exide rechargeableBattery = new Exide();
        rechargeableBattery.power();
        rechargeableBattery.charge();
        Castclass btry=new Castclass();
        btry.btry(battery);
        btry.btry(rechargeableBattery);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Tank tank = new Tank();
        tank.fire();
        Tank bttl = new BattleTank();
        bttl.fire();
        BattleTank battleTank = new BattleTank();
        battleTank.fire();
        battleTank.armor();
        Castclass btlnk=new Castclass();
        btlnk.tnk(tank);
        btlnk.tnk(battleTank);
        Bow bow = new Bow();
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        bow.shoot();
        Bow lb = new LongBow();
        lb.shoot();
        LongBow longBow = new LongBow();
        longBow.shoot();
        longBow.range();
        Castclass bo=new Castclass();
        bo.bw(bow);
        bo.bw(longBow);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Bowl bowl = new Bowl();
        bowl.hold();
        Bowl sb = new SoupBowl();
        sb.hold();
        SoupBowl soupBowl = new SoupBowl();
        soupBowl.hold();
        soupBowl.serve();
        Castclass spbl=new Castclass();
        spbl.bwl(bowl);
        spbl.bwl(soupBowl);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Rice rice = new Rice();
        rice.cook();
        Rice basmati = new BasmatiRice();
        basmati.cook();
        BasmatiRice basmatiRice = new BasmatiRice();
        basmatiRice.cook();
        basmatiRice.aroma();
        Castclass bsmt =new Castclass();
        bsmt.rce(rice);
        bsmt.rce(basmatiRice);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        BislariBottle bottle2 = new BislariBottle();
        bottle2.fill();
        BislariBottle wb = new WaterBottle();
        wb.fill();
        WaterBottle waterBottle = new WaterBottle();
        waterBottle.fill();
        waterBottle.drink();
        Castclass biwtr=new Castclass();
        biwtr.bisl(bottle2);
        biwtr.bisl(waterBottle);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Printer printer = new Printer();
        printer.print();
        Printer lp1 = new LaserPrinter();
        lp1.print();
        LaserPrinter laserPrinter = new LaserPrinter();
        laserPrinter.print();
        laserPrinter.speed();
        Castclass prt=new Castclass();
        prt.print(printer);
        prt.print(laserPrinter);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Kurtha kurtha = new Kurtha();
        kurtha.wear();
        Kurtha designer = new DesiKurtha();
        designer.wear();
        DesiKurtha designerKurtha = new DesiKurtha();
        designerKurtha.wear();
        designerKurtha.embroidery();
        Castclass dek=new Castclass();
        dek.dress(kurtha);
        dek.dress(designerKurtha);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Xerox xerox = new Xerox();
        xerox.copy();
        Xerox color = new ColorXerox();
        color.copy();
        ColorXerox colorXerox = new ColorXerox();
        colorXerox.copy();
        Castclass xrx=new Castclass();
        xrx.xrx(xerox);
        xrx.xrx(colorXerox);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Train train = new Train();
        train.move();
        Train bullet = new BulletTrain();
        bullet.move();
        BulletTrain bulletTrain = new BulletTrain();
        bulletTrain.move();
        Castclass tri=new Castclass();
        tri.trn(train);
        tri.trn(bulletTrain);
        bulletTrain.highSpeed();
        Spoon spoon = new Spoon();
        spoon.scoop();
        Spoon silver = new SilverSpoon();
        silver.scoop();
        SilverSpoon silverSpoon = new SilverSpoon();
        silverSpoon.scoop();
        silverSpoon.shine();
        Castclass spon=new Castclass();
        spon.spn(spoon);
        spon.spn(silverSpoon);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");

        Fork fork = new Fork();
        fork.pick();
        Fork salad = new SaladFork();
        salad.pick();
        SaladFork saladFork = new SaladFork();
        saladFork.pick();
        saladFork.grip();
        Castclass fr=new Castclass();
        fr.frk(fork);
        fr.frk(saladFork);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Film film = new Film();
        film.play();
        Film doc = new DocumentaryFilm();
        doc.play();
        DocumentaryFilm documentary = new DocumentaryFilm();
        documentary.play();
        documentary.educate();
        Castclass mov=new Castclass();
        mov.flm(film);
        mov.flm(documentary);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Switch sw = new Switch();
        sw.turnOn();
        Switch smart = new SmartSwitch();
        smart.turnOn();
        SmartSwitch smartSwitch = new SmartSwitch();
        smartSwitch.turnOn();
        smartSwitch.schedule();
        Castclass swt=new Castclass();
        swt.swth(sw);
        swt.swth(smartSwitch);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Pickle pickle = new Pickle();
        pickle.preserve();
        Pickle mango = new MangoPickle();
        mango.preserve();
        MangoPickle mangoPickle = new MangoPickle();
        mangoPickle.preserve();
        mangoPickle.taste();
        Castclass pik=new Castclass();
        pik.pick(pickle);
        pik.pick(mangoPickle);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Tube tube = new Tube();
        tube.squeeze();
        Tube paste = new ToothpasteTube();
        paste.squeeze();
        ToothpasteTube toothpasteTube = new ToothpasteTube();
        toothpasteTube.squeeze();
        toothpasteTube.mintFlavor();
        Castclass past=new Castclass();
        past.tb(tube);
        past.tb(toothpasteTube);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Blanket blanket = new Blanket();
        blanket.cover();
        Blanket wool = new WoolBlanket();
        wool.cover();
        WoolBlanket woolBlanket = new WoolBlanket();
        woolBlanket.cover();
        woolBlanket.warm();
        Castclass wol=new Castclass();
        wol.blank(blanket);
        wol.blank(woolBlanket);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Stand stand = new Stand();
        stand.hold();
        Stand mobile3 = new MobileStand();
        mobile3.hold();
        MobileStand mobileStand = new MobileStand();
        mobileStand.hold();
        mobileStand.rotate();
        Castclass mob=new Castclass();
        mob.std(stand);
        mob.std(mobileStand);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Bangle bangle = new Bangle();
        bangle.wear();
        Bangle gold2 = new GoldBangle();
        gold2.wear();
        GoldBangle goldBangle = new GoldBangle();
        goldBangle.wear();
        goldBangle.sparkle();
        Castclass bgnl=new Castclass();
        bgnl.bgl(bangle);
        bgnl.bgl(goldBangle);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Mirror mirror = new Mirror();
        mirror.reflect();
        Mirror wall = new WallMirror();
        wall.reflect();
        WallMirror wallMirror = new WallMirror();
        wallMirror.reflect();
        wallMirror.hang();
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Castclass mir=new Castclass();
        mir.mir(mirror);
        mir.mir(wallMirror);
        Elevator elevator = new Elevator();
        elevator.move();
        Elevator smart2 = new SmartElevator();
        smart2.move();
        SmartElevator smartElevator = new SmartElevator();
        smartElevator.move();
        Castclass ele=new Castclass();
        ele.eliv(elevator);
        ele.eliv(smartElevator);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Lamp lamp = new Lamp();
        lamp.glow();
        Lamp table2 = new TableLamp();
        table2.glow();
        TableLamp tableLamp = new TableLamp();
        tableLamp.glow();
        tableLamp.adjust();
        Castclass lmp=new Castclass();
        lmp.lmp(lamp);
        lmp.lmp(tableLamp);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Keychain keychain = new Keychain();
        keychain.holdKeys();
        Keychain digital = new DigitalKeychain();
        digital.holdKeys();
        DigitalKeychain digitalKeychain = new DigitalKeychain();
        digitalKeychain.holdKeys();
        digitalKeychain.track();
        Castclass kchi=new Castclass();
        kchi.keych(keychain);
        kchi.keych(digitalKeychain);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Keyboard keyboard = new Keyboard();
        keyboard.type();
        Keyboard mechanical = new MechanicalKeyboard();
        mechanical.type();
        MechanicalKeyboard mechKeyboard = new MechanicalKeyboard();
        mechKeyboard.type();
        Castclass key=new Castclass();
        key.key(keyboard);
        key.key(mechKeyboard);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Trimmer trimmer = new Trimmer();
        trimmer.trim();
        Trimmer beard = new BeardTrimmer();
        beard.trim();
        BeardTrimmer beardTrimmer = new BeardTrimmer();
        beardTrimmer.trim();
        beardTrimmer.adjustLength();
        Castclass trimm=new Castclass();
        trimm.trm(trimmer);
        trimm.trm(beardTrimmer);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Calendor calendor = new Calendor();
        calendor.showDate();
        Calendor digital2 = new DigitalCalendor();
        digital2.showDate();
        DigitalCalendor digitalCalendor = new DigitalCalendor();
        digitalCalendor.showDate();
        Castclass cal=new Castclass();
        cal.calend(calendor);
        cal.calend(digitalCalendor);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Spects spects = new Spects();
        spects.wear();
        Spects sun2 = new SunGlasses();
        sun2.wear();
        SunGlasses sunGlasses = new SunGlasses();
        sunGlasses.wear();
        sunGlasses.blockSunlight();
        Castclass suny=new Castclass();
        suny.spect(spects);
        suny.spect(sunGlasses);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Book book = new Book();
        book.read();
        Book ebook = new EBook();
        ebook.read();
        EBook myEBook = new EBook();
        myEBook.read();
        myEBook.download();
        Castclass red=new Castclass();
        red.arti(book);
        red.arti(ebook);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Wallet wallet = new Wallet();
        wallet.carryCash();
        Wallet digital3 = new DigitalWallet();
        digital3.carryCash();
        DigitalWallet digitalWallet = new DigitalWallet();
        digitalWallet.carryCash();
        digitalWallet.scanQR();
        Castclass walt=new Castclass();
        walt.wlt(wallet);
        walt.wlt(digitalWallet);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Perfume perfume = new Perfume();
        perfume.apply();
        Perfume spray = new BodySpray();
        spray.apply();
        BodySpray bodySpray = new BodySpray();
        bodySpray.apply();
        bodySpray.refresh();
        Castclass spry=new Castclass();
        spry.spry(perfume);
        spry.spry(bodySpray);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Hammer hammer = new Hammer();
        hammer.hit();
        Hammer sledge = new SledgeHammer();
        sledge.hit();
        SledgeHammer sledgeHammer = new SledgeHammer();
        sledgeHammer.hit();
        sledgeHammer.breakConcrete();
        Castclass hmr=new Castclass();
        hmr.ham(hammer);
        hmr.ham(sledgeHammer);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Charger charger = new Charger();
        charger.plugIn();
        Charger fast = new FastCharger();
        fast.plugIn();
        FastCharger fastCharger = new FastCharger();
        fastCharger.plugIn();
        fastCharger.quickCharge();
        Castclass chrg=new Castclass();
        chrg.charge(charger);
        chrg.charge(fastCharger);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Bat bat = new Bat();
        bat.swing();
        Bat cricket = new CricketBat();
        cricket.swing();
        CricketBat cricketBat = new CricketBat();
        cricketBat.swing();
        cricketBat.hitBall();
        Castclass crtbt=new Castclass();
        crtbt.bit(bat);
        crtbt.bit(cricketBat);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Idol idol = new Idol();
        idol.worship();
        Idol stone = new StoneIdol();
        stone.worship();
        StoneIdol stoneIdol = new StoneIdol();
        stoneIdol.worship();
        stoneIdol.polish();
        Castclass gri=new Castclass();
        gri.idl(idol);
        gri.idl(stoneIdol);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        Chilli chilli = new Chilli();
        chilli.spiceUp();
        Chilli green = new GreenChilli();
        green.spiceUp();
        GreenChilli greenChilli = new GreenChilli();
        greenChilli.spiceUp();
        greenChilli.makePickle();
        Castclass chil=new Castclass();
        chil.green(chilli);
        chil.green(greenChilli);
        System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");







    }
}
