CREATE DATABASE space;
 USE space;
  CREATE TABLE louncher(id int,louncher_name varchar(20),govt varchar(20),lounching_pad varchar(20),l_time date,budeget float);
  CREATE TABLE setelite(id CHAR ,satelite_name varchar(20),country INT,launching_vehicle varchar(15),launch_time date,Type_sat varchar(20));
  CREATE TABLE misn(id VARCHAR(10),mission_name int);
  CREATE TABLE astrot(id int ,Astronout_name int);
  CREATE TABLE direct(id int,director_name int,age int);
  
  ALTER TABLE MISN ADD COLUMN mis_time TIMESTAMP;
  ALTER TABLE MISN ADD COLUMN mis_direct int(20);
  
  ALTER TABLE louncher ADD COLUMN capacity VARCHAR(20);
  ALTER TABLE louncher ADD COLUMN fuel_for_louncher int;
  
ALTER TABLE setelite ADD COLUMN weight int ;
ALTER TABLE setelite ADD COLUMN Setelite_type VARCHAR(20);

ALTER TABLE astrot ADD COLUMN age VARCHAR(10);
ALTER TABLE astrot ADD COLUMN weight varchar(20);

ALTER TABLE direct ADD COLUMN missions VARCHAR(20);
ALTER TABLE direct ADD COLUMN experience varchar(20);

ALTER TABLE misn MODIFY COLUMN mission_name VARCHAR(20);
ALTER TABLE misn MODIFY COLUMN mis_direct VARCHAR(25);
ALTER TABLE misn MODIFY COLUMN id int;

ALTER TABLE louncher MODIFY COLUMN capacity int;
ALTER TABLE louncher MODIFY COLUMN fuel_for_louncher float;
ALTER TABLE louncher MODIFY COLUMN l_time TIMESTAMP;

ALTER TABLE astrot MODIFY COLUMN age INT ;
ALTER TABLE astrot MODIFY COLUMN weight int;
ALTER TABLE astrot MODIFY COLUMN Astronout_name VARCHAR(25);

ALTER TABLE setelite MODIFY COLUMN country VARCHAR(20);
ALTER TABLE setelite MODIFY COLUMN weight float;
ALTER TABLE setelite MODIFY COLUMN id INT;

ALTER TABLE direct MODIFY COLUMN missions int;
ALTER TABLE direct MODIFY COLUMN experience int;
ALTER TABLE direct MODIFY COLUMN director_name VARCHAR(20);

ALTER TABLE misn RENAME COLUMN mis_time TO MISSION_TIME;
ALTER TABLE misn RENAME COLUMN mis_dirEct to MISSION_DIRECTOR;
ALTER TABLE misn RENAME COLUMN ID TO MISSION_ID;

ALTER TABLE louncher RENAME COLUMN id TO ID;
ALTER TABLE louncher RENAME COLUMN fuel_for_louncher TO FUEL;
ALTER TABLE louncher RENAME COLUMN L_time to LOUNCH_TIME;

ALTER TABLE direct RENAME COLUMN missions to NO_MISSION;
ALTER TABLE direct RENAME COLUMN  director_name TO DIRECT_NAME;
 ALTER TABLE direct RENAME COLUMN age to DIRECT_AGE;

ALTER TABLE setelite RENAME COLUMN id to setelite_id;
ALTER TABLE setelite RENAME COLUMN Type_sat to selelite_type;
ALTER TABLE setelite RENAME COLUMN launch_time to time_launch;

ALTER TABLE astrot RENAME COLUMN age to Astrot_age;
ALTER TABLE astrot RENAME COLUMN Astronout_name TO astrot_name;
ALTER TABLE astrot RENAME COLUMN id to Astrot_id;

ALTER TABLE astrot DROP COLUMN weight;
ALTER TABLE misn DROP COLUMN  MISSION_TIME;
ALTER TABLE direct DROP COLUMN DIRECT_AGE;
ALTER TABLE setelite DROP COLUMN  launch_time;
ALTER TABLE louncher DROP COLUMN budeget;

use  space;

CREATE TABLE HOSPITAL_INFO(ID int,HOSPITAL_NAME VARCHAR(40),NO_WARDS INT,LOCATION VARCHAR(30),NO_SURGENS INT,CONTACT BIGINT);
INSERT into HOSPITAL_INFO values(1,'BASAWESHWARA HOSPITAL',15,'CHITHRADURGA',5,9496846938);
INSERT into HOSPITAL_INFO values(2,'DISTIRCT GOVT HOSPITAL',30,'CHITHRADURGA',8,080846938);
INSERT into HOSPITAL_INFO values(3,'DWARAKA HOSPITAL',2,'CHALLAKERE',1,988978789);
INSERT into HOSPITAL_INFO values(4,'SAINIKA HOSPITAL',10,'CHALLAKERE',2,8996846938);
INSERT into HOSPITAL_INFO values(5,'THALUK GOVT HOSPITAL',20,'CHALLAKERE',3,080684693);
INSERT into HOSPITAL_INFO values(6,'THIRUMALA HOSPITAL',15,'CHALLAKERE',7,986846938);
INSERT into HOSPITAL_INFO values(7,'VASAVI HOSPITAL',5,'CHITHRADURGA',5,9496846938);
INSERT into HOSPITAL_INFO values(8,'SSS HOSPITAL',25,'DAVANGERE',10,679846938);
INSERT into HOSPITAL_INFO values(9,'BAPUJI HOSPITAL',30,'DAVANGERE',5,786846938);
INSERT into HOSPITAL_INFO values(10,'JAYADEVA HOSPITAL',50,'BENGALURU',15,9496846938);
INSERT into HOSPITAL_INFO values(11,'SANJEEVINI HOSPITAL',2,'CHALLAKERE',1,9786846938);
INSERT into HOSPITAL_INFO values(12,'SJM HOSPITAL',12,'SIRA',4,3436846938);
INSERT into HOSPITAL_INFO values(13,'KRISHNA HOSPITAL',6,'MOLKALAMURU',2,766846938);
INSERT into HOSPITAL_INFO values(14,'KRUPA HOSPITAL',19,'SHIVAMOGGA',4,767846938);
INSERT into HOSPITAL_INFO values(15,'MANASA HOSPITAL',15,'SHIVAMOGGA',8,9546846938);
SELECT * FROM  HOSPITAL_INFO;


USE SPACE;

CREATE TABLE STATE_INFO(ID INT,STATE_NAME VARCHAR(30),PRESENT_GOVT VARCHAR(30),POPULATION varchar(20),CM_STATE VARCHAR(20),GDP float );
INSERT INTO STATE_INFO values(1,'KARNATAKA','CONGRESS','250 million','Siddaramaiah',25.00);
INSERT INTO STATE_INFO values(2,'MAHARASTRA','CONGRESS','124 MILLION','Devendra Fadnavis',38.85);
INSERT INTO STATE_INFO values(3,'TAMIL NADU','DMK','76 millio','M.K. Stalin',26.85);
INSERT INTO STATE_INFO values(4,'UTTAR PRADESH','BJP','240 million','Yogi Adityanath',24.309);
INSERT INTO STATE_INFO values(5,'GUJARAT','BJP','71 million','Bhupendrabhai Patel',25.62);
INSERT INTO STATE_INFO values(6,'WEST BENGAL','All India Trinamool Congress','100 million','Mamata Banerjee',17.19);
INSERT INTO STATE_INFO values(7,'RAJASTHAN','BJP','85 million','Nayab Singh Saini',15.70);
INSERT INTO STATE_INFO values(8,'TELENGANA','Bharat Rashtra Samithi','40 million','K. Chandrashekar Rao',14.00);
INSERT INTO STATE_INFO values(9,'ANDRA PRADESH','TDP','54 million','N. Chandrababu Naidu',14.49);
INSERT INTO STATE_INFO values(10,'MADYA PRADESH','BJP','87 million','Mohan Yadav',13.89);
INSERT INTO STATE_INFO values(11,'KERALA','CPOI ','36 million','Pinarayi Vijayan',11.30);
INSERT INTO STATE_INFO values(12,'HARYANA','BJP','30.6','Nayab Singh Saini',11.20);
INSERT INTO STATE_INFO values(13,'DELHI','BJP','33.8 million','Rekha Gupta',10.40);
INSERT INTO STATE_INFO values(14,'PUNJAB','AamAadmiParty','31 million','Bhagwant Mann',6.98);
INSERT INTO STATE_INFO values(15,'BIHAR','Janata dal','127 million','Nitish Kumar',8.59);

/*DROP TABLE STATE_INFO;*/
select * from State_info;

CREATE TABLE COUNTRY_INFO(ID INT,COUNTRY_NAME VARCHAR(30),PREISDENT VARCHAR(30),CONTINET VARCHAR(20),CURRENCY VARCHAR(20),POPULATION VARCHAR(20));
INSERT INTO COUNTRY_INFO VALUES(1,'INDIA','DROUPADI MURMU','ASIA','INDIAN RUPEE','1.37 billion');
INSERT INTO COUNTRY_INFO VALUES(2,'CHINA','XI PING','ASIA','YUAN','1.41');
INSERT INTO COUNTRY_INFO VALUES(3,'USA','TRUMP','NORTH AMERICA','US DOLLER','332 MILLION');
INSERT INTO COUNTRY_INFO VALUES(4,'PAKISTHAN','ARIF ALVI','PAKISTHANI RUPEE','ASIA','225 MILLION');
INSERT INTO COUNTRY_INFO VALUES(5,'BRAZIL','BOLSONARO','SOUTH AMERICA','BRAZILIAN REAL','213 MILLION');
INSERT INTO COUNTRY_INFO VALUES(6,'NIGERIA','MUHAMMADU BUHARI','AFRICA', 'NAIRA','211 MILLION');
INSERT INTO COUNTRY_INFO VALUES(7,'BANGLADESH','ABDUL HAMID','ASIA','TAKA','166 MILLION');
INSERT INTO COUNTRY_INFO VALUES(8,'RUSSIA','VLADMIR PUTIN','ASIA','RUSSIAN RUBLE','146 MILLION');
INSERT INTO COUNTRY_INFO VALUES(9,'MEXICO','ANDRES MANUEL','NORTH AMERIACA','MEXICAN PESO','130 MILLION');
INSERT INTO COUNTRY_INFO VALUES(10,'JAPAN0','SHINZO ABE','ASIA','YEN','125 MILLION');
INSERT INTO COUNTRY_INFO VALUES(11,'ETHOPIA','SHALE','AFRICA','BIRR','120 MILLION');
INSERT INTO COUNTRY_INFO VALUES(12,'PHILIPPINES','RODRIGO DUTRETE','ASIA','PESO','113MILLION');
INSERT INTO COUNTRY_INFO VALUES(13,'EGYPT','ABDEL FATTAH','AFRICA','EGYPT POUND','109 MILLION');
INSERT INTO COUNTRY_INFO VALUES(14,'VIETNAM','Nguyễn Phú Trọng','ASIA','DONG','98 MILLION'); 
INSERT INTO COUNTRY_INFO VALUES(15,'INDONASIA','Joko Widodo','ASIA','RUPIAH','276 MILLION');


drop table COUNTRY_INFO;

SELECT * FROM COUNTRY_INFO;


use space;
select * from  COUNTRY_INFO;

SELECT  * FROM COUNTRY_INFO where CONTINET='ASIA';
SELECT  * FROM COUNTRY_INFO WHERE CONTINET='ASIA' AND COUNTRY_NAME='INDIA';
SELECT * FROM STATE_INFO WHERE PRESENT_GOVT='BJP' or PRESENT_GOVT='CONGRESS';
SELECT STATE_NAME from STATE_INFO where PRESENT_GOVT='congress' and CM_STATE='Siddaramaiah';
SELECT CURRENCY FROM COUNTRY_INFO WHERE COUNTRY_NAME='VIETNAM' AND CONTINET='ASIA' OR ID=14;
SELECT POPULATION FROM COUNTRY_INFO where COUNTRY_NAME='USA' or PREISDENT='trump';
select * from COUNTRY_INFO where COUNTRY_NAME='UK' AND ID=3  OR CONTINET='NORTH AMERICA';
SELECT * FROM COUNTRY_INFO WHERE ID=2 AND CONTINET='ASIA'; 


/*IN AND NOT IN OPERATIONS*/
SELECT * FROM COUNTRY_INFO WHERE CONTINET IN ('ASIA','AFRICA');
SELECT * FROM COUNTRY_INFO WHERE CONTINET NOT IN('ASIA','NORTH AMERICA');
SELECT * FROM COUNTRY_INFO WHERE ID IN(2,4,5,9,14);
SELECT * FROM COUNTRY_INFO WHERE CURRENCY NOT IN ('US DOLLER','YEN');

SELECT * FROM STATE_INFO WHERE ID IN(1,3,2,7,12,10); 
SELECT * FROM STATE_INFO WHERE PRESENT_GOVT NOT IN('BJP','CONGRESS');
SELECT * FROM STATE_INFO WHERE PRESENT_GOVT IN ('BJP'); 
SELECT * FROM STATE_INFO WHERE GDP  IN(6.98);

SELECT * FROM HOSPITAL_INFO WHERE LOCATION IN ('CHALLAKERE');
SELECT * FROM HOSPITAL_INFO WHERE NO_SURGENS NOT IN(1,2,3);
SELECT * FROM HOSPITAL_INFO WHERE LOCATION NOT IN('DAVANGERE','CHITHRADURGA','CHALLAKERE');
SELECT * FROM HOSPITAL_INFO WHERE NO_WARDS IN (1,5,8,25); 

SELECT * FROM COUNTRY_INFO WHERE ID between 1 AND 4;
SELECT * FROM COUNTRY_INFO WHERE ID NOT BETWEEN 1 AND 10;

SELECT * FROM STATE_INFO WHERE GDP BETWEEN 20 AND 30;
SELECT * FROM STATE_INFO WHERE GDP NOT BETWEEN 1 AND 15;

SELECT * FROM HOSPITAL_INFO WHERE NO_WARDS BETWEEN 15 AND 30; 
SELECT * FROM HOSPITAL_INFO WHERE NO_WARDS NOT BETWEEN 1 AND 5;

UPDATE HOSPITAL_INFO SET NO_WARDS=40 WHERE LOCATION='CHALLAKERE' AND HOSPITAL_NAME='THALUK GOVT HOSPITAL';
UPDATE HOSPITAL_INFO SET NO_WARDS=10 WHERE LOCATION='CHITHRADURGA' AND HOSPITAL_NAME='VASAVI HOSPITAL';

UPDATE STATE_INFO SET POPULATION='260 million' where state_name='KARNATAKA' and ID=1;
UPDATE STATE_INFO SET PRESENT_GOVT='BJP' WHERE STATE_NAME='KARNATAKA' AND CM_STATE='Siddaramaiah';

UPDATE COUNTRY_INFO SET COUNTRY_NAME='BHARATH' WHERE CONTINET='ASIA' AND PREISDENT='DROUPADI MURMU';
UPDATE COUNTRY_INFO SET COUNTRY_NAME='UNITED STATES OF AMREICA' WHERE CONTINET='NORTH AMERICA' AND PREISDENT='TRUMP'