CREATE TABLE CRICKET_INFO(ID INT,LOCATION VARCHAR(25),TEAM_A VARCHAR(20),TEAM_B VARCHAR(20),MANAGEMENT VARCHAR(20),_TYPE VARCHAR(20),CAPTAINA VARCHAR(25),CAPTAINB VARCHAR(20),M_DATE VARCHAR(10),COACH_ VARCHAR(30),COACH VARCHAR(30));
/*DROP TABLE CRICKET_INFO;*/

ALTER TABLE CRICKET_INFO ADD COLUMN VICE_CAPTAIN1 VARCHAR(20);
ALTER TABLE CRICKET_INFO ADD COLUMN VICE_CAPTAIN2 VARCHAR(20);
select* FROM CRICKET_INFO;
ALTER TABLE CRICKET_INFO RENAME column ID TO MATCH_ID;
ALTER TABLE CRICKET_INFO RENAME column _TYPE TO MATCH_TYPE;
ALTER TABLE CRICKET_INFO RENAME column COACH TO COACH_A;
ALTER TABLE CRICKET_INFO RENAME column COACH_ TO COACH_B;


INSERT INTO CRICKET_INFO VALUES(1,'BENGALURU','RCB','CSK','IPL MANAGEMENT','T20 IPL','VIRAT','MS DHONI','2025-03-12','DK','CHANDRA','ABD','RAINA');
INSERT INTO CRICKET_INFO VALUES(2,'HYDRABAD','SRH','KKR','IPL MANAGEMENT','T20 IPL','BHUVANESHWAR','PANADYA','2025-12-09','V R VARMA','J K','WARNER','RUSSSEL');
INSERT INTO CRICKET_INFO VALUES(3,'DELHI','DC','MI','IPL MAMANGEMENT','T20 IPL','HARTHIK PANDYA','ROHITH S','2024-08-11','SACHIN','MANAGAL','PATEL','ISHAN');
INSERT INTO CRICKET_INFO VALUES(4,'CHENNAI','CSK','SRH','IPL MANAGEMENT','T20 IPL','MS DHONI','BHUVANESHWAR','2022-12-09','JAI ','KTRUNAL','RAINA','WARNER');
INSERT INTO CRICKET_INFO VALUES(5,'AHAMADABAD','K11P','RCB','IPL MANAGEMENT','T20 IPL','K L RAHUL','VIRAT','2022-02-23','UDAYSINGH','DK','GAYEL','ABD');
INSERT INTO CRICKET_INFO VALUES(6,'MUMBAI','MI','RR','IPL MANAGEMENT','T20 IPL','ROHIT SHARMA','SANJU SAMSON','2023-04-15','SURYA','BUTTLER','BOULT','BUMRAH');
INSERT INTO CRICKET_INFO VALUES(7,'KOLKATA','KKR','DC','IPL MANAGEMENT','T20 IPL','NITISH RANA','RISABH PANT','2024-06-22','RUSSELL','WARNER','NARINE','SHAW');
INSERT INTO CRICKET_INFO VALUES(8,'AHMEDABAD','GT','LSG','IPL MANAGEMENT','T20 IPL','HARDIK PANDYA','KL RAHUL','2025-05-10','GILL','STOINIS','MOHSIN','SHAMI');
INSERT INTO CRICKET_INFO VALUES(9,'PUNE','CSK','GT','IPL MANAGEMENT','T20 IPL','JADEJA','GILL','2024-09-05','CHAHAR','TITAN','RAHANE','FERGUSON');
INSERT INTO CRICKET_INFO VALUES(10,'RAJASTHAN','RR','SRH','IPL MANAGEMENT','T20 IPL','BUTTLER','BHUVANESHWAR','2023-07-19','SAMSOM','PARAG','JANSEN','CHAHAL');
INSERT INTO CRICKET_INFO VALUES(11,'LUCKNOW','LSG','KKR','IPL MANAGEMENT','T20 IPL','STOINIS','RUSSELL','2024-10-14','RAHUL','BADONI','VARUN','CUMMINS');
INSERT INTO CRICKET_INFO VALUES(12,'MOHALI','PBKS','MI','IPL MANAGEMENT','T20 IPL','SHAIKH','ISHAN','2025-08-08','RAHUL','LIVINGSTONE','BUMRAH','SURYA');
INSERT INTO CRICKET_INFO VALUES(13,'GUWAHATI','RR','RCB','IPL MANAGEMENT','T20 IPL','SANJU SAMSON','VIRAT','2023-11-29','BUTTLER','MAXWELL','CHAHAL','HASARANGA');
INSERT INTO CRICKET_INFO VALUES(14,'KANPUR','SRH','DC','IPL MANAGEMENT','T20 IPL','MARKRAM','PANT','2024-12-12','WARNER','BROOKS','ISHAN','SHAW');
INSERT INTO CRICKET_INFO VALUES(15,'INDORE','MI','CSK','IPL MANAGEMENT','T20 IPL','ROHIT','DHONI','2025-01-26','SURYA','JADEJA','BUMRAH','THAKUR');


select* FROM CRICKET_INFO;


UPDATE CRICKET_INFO SET LOCATION='BENGALORE' WHERE MATCH_ID=1 AND TEAM_A='RCB' OR VICE_CAPTAIN1='ABD';
UPDATE CRICKET_INFO SET CAPTAINA='WARNER' WHERE MATCH_ID=2 AND TEAM_A='SRH' OR VICE_CAPTAIN1='WARNER';
UPDATE CRICKET_INFO SET COACH_B='DINESH KARTHIK' WHERE MATCH_ID=5 AND TEAM_B='RCB' OR CAPTAINB='VIRAT';
UPDATE CRICKET_INFO SET LOCATION='HYDRABAD' WHERE TEAM_A='SRH'AND M_DATE='2024-12-12' OR VICE_CAPTAIN1='ISHAN';
UPDATE CRICKET_INFO SET M_DATE='2019-12-02' WHERE MATCH_ID=1 AND TEAM_A='RCB' OR VICE_CAPTAIN1='ABD';

SELECT * FROM CRICKET_INFO WHERE TEAM_A='DC' AND TEAM_B='MI' OR CAPTAINA='HARTHIK PANDYA';
SELECT * FROM CRICKET_INFO WHERE LOCATION='BENGALORE' AND CAPTAINA='VIRAT' OR VICE_CAPTAIN1='ABD';
SELECT * FROM CRICKET_INFO WHERE TEAM_A IN('RCB','GT');
SELECT * FROM CRICKET_INFO WHERE CAPTAINA IN('VIRAT','MS DHONI');
SELECT * FROM CRICKET_INFO WHERE LOCATION NOT IN('CHENNAI','MUMBAI');
SELECT * FROM CRICKET_INFO WHERE TEAM_A NOT IN('CSK');

SELECT * FROM CRICKET_INFO WHERE MATCH_ID BETWEEN 5 AND 10;
SELECT * FROM CRICKET_INFO WHERE MATCH_ID NOT BETWEEN 10 AND 15;

SELECT * FROM CRICKET_INFO WHERE TEAM_A LIKE 'R%';
SELECT * FROM CRICKET_INFO WHERE CAPTAINA LIKE 'S%';
SELECT * FROM CRICKET_INFO WHERE TEAM_A  NOT LIKE 'C%';
SELECT * FROM CRICKET_INFO WHERE CAPTAINB  LIKE 'R%';

DROP TABLE FOOTBALL_INFO;

CREATE TABLE FOOTBALL_INFO ( ID INT,LOCATION VARCHAR(25),TEAM_A VARCHAR(20),TEAM_B VARCHAR(20),MANAGEMENT VARCHAR(20),LEAGUE_TYPE VARCHAR(20),CAPTAIN_A VARCHAR(25),CAPTAIN_B VARCHAR(20),COACH_A VARCHAR(30),COACH_B VARCHAR(30));
ALTER TABLE FOOTBALL_INFO ADD column MATCH_DATE VARCHAR(10);
ALTER TABLE FOOTBALL_INFO ADD column COUNTRY VARCHAR(20);

ALTER TABLE FOOTBALL_INFO RENAME column LOCATION TO MATCH_LOCATION;
ALTER TABLE FOOTBALL_INFO RENAME COLUMN ID TO MATCH_ID;
ALTER TABLE FOOTBALL_INFO RENAME COLUMN MANAGEMENT TO MANAGE;

INSERT INTO FOOTBALL_INFO VALUES (1, 'Manchester','Man United', 'Chelsea', 'EPL', 'Premier League', 'Bruno Fernandes', 'Reece James', 'Erik ten Hag', 'Pochettino', 'England', '2025-03-15');
INSERT INTO FOOTBALL_INFO VALUES (2, 'Madrid','Real Madrid', 'Barcelona', 'La Liga', 'La Liga', 'Luka Modric', 'Sergi Roberto', 'Ancelotti', 'Xavi', 'Spain', '2025-04-10');
INSERT INTO FOOTBALL_INFO VALUES (3, 'Munich','Bayern Munich', 'Dortmund', 'Bundesliga', 'Bundesliga', 'Neuer', 'Reus', 'Tuchel', 'Terzic', 'Germany', '2025-05-05');
INSERT INTO FOOTBALL_INFO VALUES (4, 'Paris','PSG', 'Marseille', 'Ligue 1', 'Ligue 1', 'Mbappe', 'Payet', 'Luis Enrique', 'Igor Tudor', 'France', '2025-06-18');
INSERT INTO FOOTBALL_INFO VALUES (5, 'Turin','Juventus', 'AC Milan', 'Serie A', 'Serie A', 'Danilo', 'Calabria', 'Allegri', 'Pioli', 'Italy', '2025-07-21');
INSERT INTO FOOTBALL_INFO VALUES (6, 'London','Arsenal', 'Liverpool', 'EPL', 'Premier League', 'Ødegaard', 'Van Dijk', 'Arteta', 'Klopp', 'England', '2025-08-12');
INSERT INTO FOOTBALL_INFO VALUES (7, 'Manchester','Man City', 'Tottenham', 'EPL', 'Premier League', 'De Bruyne', 'Son', 'Guardiola', 'Postecoglou', 'England', '2025-09-25');
INSERT INTO FOOTBALL_INFO VALUES (8, 'Milan','Inter Milan', 'Napoli', 'Serie A', 'Serie A', 'Martinez', 'Di Lorenzo', 'Inzaghi', 'Calzona', 'Italy', '2025-10-30');
INSERT INTO FOOTBALL_INFO VALUES (9, 'Dortmund','Dortmund', 'Leipzig', 'Bundesliga', 'Bundesliga', 'Emre Can', 'Willi Orban', 'Terzic', 'Rose', 'Germany', '2025-11-14');
INSERT INTO FOOTBALL_INFO VALUES (10, 'Barcelona','Barcelona', 'Atletico', 'La Liga', 'La Liga', 'De Jong', 'Koke', 'Xavi', 'Simeone', 'Spain', '2025-12-05');
INSERT INTO FOOTBALL_INFO VALUES (11, 'Seville','Sevilla', 'Real Betis', 'La Liga', 'La Liga', 'Jesus Navas', 'Rodriguez', 'Mendilibar', 'Pellegrini', 'Spain', '2026-01-18');
INSERT INTO FOOTBALL_INFO VALUES (12, 'Lisbon','Benfica', 'Porto', 'Primeira Liga', 'Primeira Liga', 'João Mário', 'Pepe', 'Schmidt', 'Conceição', 'Portugal', '2026-02-05');
INSERT INTO FOOTBALL_INFO VALUES (13, 'Amsterdam','Ajax', 'PSV', 'Eredivisie', 'Eredivisie', 'Bergwijn', 'Luuk de Jong', 'Van ’t Schip', 'Bosz', 'Netherlands', '2022-03-10');
INSERT INTO FOOTBALL_INFO VALUES (14, 'Buenos Aires','Boca Juniors', 'River Plate', 'Superclásico', 'Argentine League', 'Rojo', 'Enzo Pérez', 'Almirón', 'Demichelis', 'Argentina', '2026-04-22');
INSERT INTO FOOTBALL_INFO VALUES (15, 'New York','NYC FC', 'LA Galaxy', 'MLS', 'Major League Soccer', 'James Sands', 'Riqui Puig', 'Cushing', 'Vanney', 'USA', '2026-05-15');

SELECT * FROM FOOTBALL_INFO;
UPDATE FOOTBALL_INFO SET TEAM_A='PSG' WHERE match_ID=1 AND MANAGE='EPL';
UPDATE FOOTBALL_INFO SET MANAGE='LIGUIE 1' WHERE match_ID=6 AND MATCH_LOCATION='PARIS';
UPDATE FOOTBALL_INFO SET TEAM_B='LIVERPOOL' WHERE match_ID=3 AND MANAGE='Bundesliga';
UPDATE FOOTBALL_INFO SET MATCH_DATE='PSG' WHERE match_ID=13 AND COUNTRY='NETHERLAND';


select* FROM FOOTBALL_INFO WHERE MATCH_ID=8 AND COACH_A='Inzaghi' OR COACH_B='Calzona';
select* FROM FOOTBALL_INFO WHERE MATCH_DATE='2025-08-12' OR COUNTRY='ENGLAND';
select * FROM FOOTBALL_INFO WHERE COUNTRY='ITALY' AND MATCH_LOCATION='MILAN' OR COACH_A='inzaghi';
select * FROM FOOTBALL_INFO WHERE MATCH_DATE IN('2025-05-05','2025-09-25','2025-11-14','2026-04-22');
select * FROM FOOTBALL_INFO WHERE MATCH_DATE NOT IN('2026-02-05','2025-09-25','2025-11-14','2026-05-15');
SELECT * FROM FOOTBALL_INFO WHERE MATCH_ID between 4 AND 9;
SELECT * FROM FOOTBALL_INFO WHERE MATCH_ID NOT between 10 AND 15;

SELECT * FROM FOOTBALL_INFO WHERE MATCH_LOCATION LIKE 'M%';
SELECT * FROM FOOTBALL_INFO WHERE MATCH_LOCATION LIKE '%N';
SELECT * FROM FOOTBALL_INFO WHERE MATCH_DATE NOT LIKE '%5';
SELECT * FROM FOOTBALL_INFO WHERE MANAGE LIKE 'S%';


